# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cPatches.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Patches(object):
    def setupUi(self, Patches):
        Patches.setObjectName("Patches")
        Patches.resize(592, 580)
        self.buttonBox = QtWidgets.QDialogButtonBox(Patches)
        self.buttonBox.setGeometry(QtCore.QRect(220, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Patches)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 541, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 231, 171))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.b_21 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_21.setText("")
        self.b_21.setObjectName("b_21")
        self.gridLayout_3.addWidget(self.b_21, 3, 1, 1, 1)
        self.t1 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.t1.setObjectName("t1")
        self.gridLayout_3.addWidget(self.t1, 1, 0, 1, 1)
        self.trans1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.trans1.setObjectName("trans1")
        self.gridLayout_3.addWidget(self.trans1, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.b_22 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_22.setText("")
        self.b_22.setObjectName("b_22")
        self.gridLayout_3.addWidget(self.b_22, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        self.t2 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.t2.setObjectName("t2")
        self.gridLayout_3.addWidget(self.t2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 231, 293))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.ggglayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.ggglayout.setContentsMargins(0, 0, 0, 0)
        self.ggglayout.setObjectName("ggglayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.ggglayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setObjectName("label")
        self.ggglayout.addWidget(self.label, 7, 0, 1, 1)
        self.b_81 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.b_81.setText("")
        self.b_81.setObjectName("b_81")
        self.ggglayout.addWidget(self.b_81, 3, 1, 1, 1)
        self.trans2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.trans2.setObjectName("trans2")
        self.ggglayout.addWidget(self.trans2, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.ggglayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.ggglayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.b_82 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.b_82.setText("")
        self.b_82.setObjectName("b_82")
        self.ggglayout.addWidget(self.b_82, 4, 1, 1, 1)
        self.i2 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.i2.setObjectName("i2")
        self.ggglayout.addWidget(self.i2, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.ggglayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.i1 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.i1.setObjectName("i1")
        self.ggglayout.addWidget(self.i1, 1, 0, 1, 1)
        self.b_83 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.b_83.setText("")
        self.b_83.setObjectName("b_83")
        self.ggglayout.addWidget(self.b_83, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.ggglayout.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.ggglayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.ggglayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.cb_81 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cb_81.setObjectName("cb_81")
        self.cb_81.addItem("")
        self.cb_81.addItem("")
        self.cb_81.addItem("")
        self.cb_81.addItem("")
        self.cb_81.addItem("")
        self.ggglayout.addWidget(self.cb_81, 7, 1, 1, 1)
        self.cb_82 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cb_82.setObjectName("cb_82")
        self.cb_82.addItem("")
        self.cb_82.addItem("")
        self.cb_82.addItem("")
        self.cb_82.addItem("")
        self.cb_82.addItem("")
        self.ggglayout.addWidget(self.cb_82, 8, 1, 1, 1)
        self.cb_83 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cb_83.setObjectName("cb_83")
        self.cb_83.addItem("")
        self.cb_83.addItem("")
        self.cb_83.addItem("")
        self.cb_83.addItem("")
        self.cb_83.addItem("")
        self.ggglayout.addWidget(self.cb_83, 9, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 231, 363))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.b_115 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_115.setText("")
        self.b_115.setObjectName("b_115")
        self.gridLayout_2.addWidget(self.b_115, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.b_113 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_113.setText("")
        self.b_113.setObjectName("b_113")
        self.gridLayout_2.addWidget(self.b_113, 5, 1, 1, 1)
        self.b_114 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_114.setText("")
        self.b_114.setObjectName("b_114")
        self.gridLayout_2.addWidget(self.b_114, 6, 1, 1, 1)
        self.b_111 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_111.setText("")
        self.b_111.setObjectName("b_111")
        self.gridLayout_2.addWidget(self.b_111, 3, 1, 1, 1)
        self.b_112 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_112.setText("")
        self.b_112.setObjectName("b_112")
        self.gridLayout_2.addWidget(self.b_112, 4, 1, 1, 1)
        self.trans3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.trans3.setObjectName("trans3")
        self.gridLayout_2.addWidget(self.trans3, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 10, 0, 1, 1)
        self.e1 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.e1.setObjectName("e1")
        self.gridLayout_2.addWidget(self.e1, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.e2 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.e2.setObjectName("e2")
        self.gridLayout_2.addWidget(self.e2, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 11, 0, 1, 1)
        self.cb_111 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cb_111.setObjectName("cb_111")
        self.cb_111.addItem("")
        self.cb_111.addItem("")
        self.cb_111.addItem("")
        self.cb_111.addItem("")
        self.cb_111.addItem("")
        self.gridLayout_2.addWidget(self.cb_111, 9, 1, 1, 1)
        self.cb_112 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cb_112.setObjectName("cb_112")
        self.cb_112.addItem("")
        self.cb_112.addItem("")
        self.cb_112.addItem("")
        self.cb_112.addItem("")
        self.cb_112.addItem("")
        self.gridLayout_2.addWidget(self.cb_112, 10, 1, 1, 1)
        self.cb_113 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cb_113.setObjectName("cb_113")
        self.cb_113.addItem("")
        self.cb_113.addItem("")
        self.cb_113.addItem("")
        self.cb_113.addItem("")
        self.cb_113.addItem("")
        self.gridLayout_2.addWidget(self.cb_113, 11, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)

        self.retranslateUi(Patches)
        self.stackedWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(Patches.accept)
        self.buttonBox.rejected.connect(Patches.reject)
        QtCore.QMetaObject.connectSlotsByName(Patches)

    def retranslateUi(self, Patches):
        _translate = QtCore.QCoreApplication.translate
        Patches.setWindowTitle(_translate("Patches", "setting"))
        self.label_14.setText(_translate("Patches", "reference"))
        self.label_17.setText(_translate("Patches", "2 classes"))
        self.t1.setText(_translate("Patches", "default"))
        self.label_16.setText(_translate("Patches", "artifacts"))
        self.label_15.setText(_translate("Patches", "transparency (0~1)"))
        self.t2.setText(_translate("Patches", "DIY"))
        self.label_2.setText(_translate("Patches", "shim"))
        self.label.setText(_translate("Patches", "movement"))
        self.label_20.setText(_translate("Patches", "head"))
        self.label_21.setText(_translate("Patches", "8 classes"))
        self.i2.setText(_translate("Patches", "DIY"))
        self.label_11.setText(_translate("Patches", "liver"))
        self.i1.setText(_translate("Patches", "default"))
        self.label_18.setText(_translate("Patches", "transparency (0~1)"))
        self.label_19.setText(_translate("Patches", "abdomen"))
        self.label_3.setText(_translate("Patches", "both"))
        self.cb_81.setItemText(0, _translate("Patches", "//"))
        self.cb_81.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_81.setItemText(2, _translate("Patches", "XX"))
        self.cb_81.setItemText(3, _translate("Patches", "--"))
        self.cb_81.setItemText(4, _translate("Patches", "**"))
        self.cb_82.setItemText(0, _translate("Patches", "//"))
        self.cb_82.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_82.setItemText(2, _translate("Patches", "XX"))
        self.cb_82.setItemText(3, _translate("Patches", "--"))
        self.cb_82.setItemText(4, _translate("Patches", "**"))
        self.cb_83.setItemText(0, _translate("Patches", "//"))
        self.cb_83.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_83.setItemText(2, _translate("Patches", "XX"))
        self.cb_83.setItemText(3, _translate("Patches", "--"))
        self.cb_83.setItemText(4, _translate("Patches", "**"))
        self.label_5.setText(_translate("Patches", "t1 head"))
        self.label_4.setText(_translate("Patches", "11 classes"))
        self.label_8.setText(_translate("Patches", "t1 liver"))
        self.label_6.setText(_translate("Patches", "t1 abdomen"))
        self.label_10.setText(_translate("Patches", "transparency (0~1)"))
        self.label_13.setText(_translate("Patches", "shim"))
        self.e1.setText(_translate("Patches", "default"))
        self.label_7.setText(_translate("Patches", "t2 abdomen"))
        self.label_9.setText(_translate("Patches", "t2 liver"))
        self.e2.setText(_translate("Patches", "DIY"))
        self.label_12.setText(_translate("Patches", "movement"))
        self.label_22.setText(_translate("Patches", "both"))
        self.cb_111.setItemText(0, _translate("Patches", "//"))
        self.cb_111.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_111.setItemText(2, _translate("Patches", "XX"))
        self.cb_111.setItemText(3, _translate("Patches", "--"))
        self.cb_111.setItemText(4, _translate("Patches", "**"))
        self.cb_112.setItemText(0, _translate("Patches", "//"))
        self.cb_112.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_112.setItemText(2, _translate("Patches", "XX"))
        self.cb_112.setItemText(3, _translate("Patches", "--"))
        self.cb_112.setItemText(4, _translate("Patches", "**"))
        self.cb_113.setItemText(0, _translate("Patches", "//"))
        self.cb_113.setItemText(1, _translate("Patches", "\\\\"))
        self.cb_113.setItemText(2, _translate("Patches", "XX"))
        self.cb_113.setItemText(3, _translate("Patches", "--"))
        self.cb_113.setItemText(4, _translate("Patches", "**"))
        self.label_23.setText(_translate("Patches", "view setting"))

