# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cPatches.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Patches(object):
    def setupUi(self, Patches):
        Patches.setObjectName("Patches")
        Patches.resize(523, 656)
        self.buttonBox = QtWidgets.QDialogButtonBox(Patches)
        self.buttonBox.setGeometry(QtCore.QRect(10, 600, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Patches)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 146, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.colorlinepos = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.colorlinepos.setObjectName("colorlinepos")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.colorlinepos.addItem("")
        self.gridLayout.addWidget(self.colorlinepos, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Patches)
        self.stackedWidget.setGeometry(QtCore.QRect(190, 110, 291, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 241, 191))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.t1 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.t1.setObjectName("t1")
        self.gridLayout_3.addWidget(self.t1, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.t2 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.t2.setObjectName("t2")
        self.gridLayout_3.addWidget(self.t2, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 5, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 241, 291))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.e1 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.e1.setObjectName("e1")
        self.gridLayout_2.addWidget(self.e1, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 6, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.e2 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.e2.setObjectName("e2")
        self.gridLayout_2.addWidget(self.e2, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 8, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.listWidget = QtWidgets.QListWidget(Patches)
        self.listWidget.setGeometry(QtCore.QRect(20, 130, 121, 191))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Patches)
        self.stackedWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Patches.accept)
        self.buttonBox.rejected.connect(Patches.reject)
        QtCore.QMetaObject.connectSlotsByName(Patches)

    def retranslateUi(self, Patches):
        _translate = QtCore.QCoreApplication.translate
        Patches.setWindowTitle(_translate("Patches", "Dialog"))
        self.label_2.setText(_translate("Patches", "line"))
        self.colorlinepos.setItemText(0, _translate("Patches", "1"))
        self.colorlinepos.setItemText(1, _translate("Patches", "2"))
        self.colorlinepos.setItemText(2, _translate("Patches", "3"))
        self.colorlinepos.setItemText(3, _translate("Patches", "4"))
        self.colorlinepos.setItemText(4, _translate("Patches", "5"))
        self.colorlinepos.setItemText(5, _translate("Patches", "6"))
        self.colorlinepos.setItemText(6, _translate("Patches", "7"))
        self.colorlinepos.setItemText(7, _translate("Patches", "8"))
        self.label.setText(_translate("Patches", "position"))
        self.t1.setText(_translate("Patches", "default color"))
        self.label_16.setText(_translate("Patches", "artefacts"))
        self.t2.setText(_translate("Patches", "DIY color"))
        self.label_15.setText(_translate("Patches", "transparency (0~1)"))
        self.pushButton_10.setText(_translate("Patches", "modify"))
        self.label_14.setText(_translate("Patches", "normal"))
        self.pushButton_11.setText(_translate("Patches", "modify"))
        self.label_17.setText(_translate("Patches", "2 classes"))
        self.e1.setText(_translate("Patches", "default color"))
        self.label_9.setText(_translate("Patches", "t2 liver"))
        self.pushButton_5.setText(_translate("Patches", "modify"))
        self.pushButton_4.setText(_translate("Patches", "modify"))
        self.label_7.setText(_translate("Patches", "t2 abdomen"))
        self.label_8.setText(_translate("Patches", "t1 liver"))
        self.pushButton_6.setText(_translate("Patches", "modify"))
        self.label_5.setText(_translate("Patches", "t1 head"))
        self.pushButton_2.setText(_translate("Patches", "modify"))
        self.label_10.setText(_translate("Patches", "transparency (0~1)"))
        self.label_6.setText(_translate("Patches", "t1 abdomen"))
        self.e2.setText(_translate("Patches", "DIY color"))
        self.pushButton_3.setText(_translate("Patches", "modify"))
        self.label_4.setText(_translate("Patches", "11 classes"))

