# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editlabel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_label(object):
    def setupUi(self, edit_label):
        edit_label.setObjectName("edit_label")
        edit_label.resize(294, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(edit_label)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.b1 = QtWidgets.QPushButton(edit_label)
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.b1)
        self.b2 = QtWidgets.QPushButton(edit_label)
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.b2)
        self.b3 = QtWidgets.QPushButton(edit_label)
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.b3)
        self.b4 = QtWidgets.QPushButton(edit_label)
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.b4)
        self.b5 = QtWidgets.QPushButton(edit_label)
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.b5)
        self.b6 = QtWidgets.QPushButton(edit_label)
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.b6)
        self.b7 = QtWidgets.QPushButton(edit_label)
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.b7)
        self.b8 = QtWidgets.QPushButton(edit_label)
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.b8)
        self.lineEdit = QtWidgets.QLineEdit(edit_label)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(edit_label)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.breset = QtWidgets.QPushButton(edit_label)
        self.breset.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/reset2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.breset.setIcon(icon)
        self.breset.setObjectName("breset")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.breset)
        self.bsetpath = QtWidgets.QPushButton(edit_label)
        self.bsetpath.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/file2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bsetpath.setIcon(icon1)
        self.bsetpath.setObjectName("bsetpath")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bsetpath)
        self.pathline = QtWidgets.QLineEdit(edit_label)
        self.pathline.setObjectName("pathline")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pathline)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(edit_label)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(edit_label)
        self.buttonBox.accepted.connect(edit_label.accept)
        self.buttonBox.rejected.connect(edit_label.reject)
        QtCore.QMetaObject.connectSlotsByName(edit_label)

    def retranslateUi(self, edit_label):
        _translate = QtCore.QCoreApplication.translate
        edit_label.setWindowTitle(_translate("edit_label", "Edit labels"))

import resrc_rc
