# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framework1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 753)
        MainWindow.setAcceptDrops(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.linebox = QtWidgets.QComboBox(self.tab_3)
        self.linebox.setObjectName("linebox")
        self.linebox.addItem("")
        self.linebox.addItem("")
        self.linebox.addItem("")
        self.gridLayout_2.addWidget(self.linebox, 2, 1, 1, 1)
        self.openfile = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openfile.sizePolicy().hasHeightForWidth())
        self.openfile.setSizePolicy(sizePolicy)
        self.openfile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/eye1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openfile.setIcon(icon)
        self.openfile.setIconSize(QtCore.QSize(35, 35))
        self.openfile.setObjectName("openfile")
        self.gridLayout_2.addWidget(self.openfile, 4, 1, 1, 1)
        self.bpatch = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpatch.sizePolicy().hasHeightForWidth())
        self.bpatch.setSizePolicy(sizePolicy)
        self.bpatch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bpatch.setIcon(icon1)
        self.bpatch.setIconSize(QtCore.QSize(35, 35))
        self.bpatch.setObjectName("bpatch")
        self.gridLayout_2.addWidget(self.bpatch, 6, 0, 1, 1)
        self.brectangle = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brectangle.sizePolicy().hasHeightForWidth())
        self.brectangle.setSizePolicy(sizePolicy)
        self.brectangle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/Rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brectangle.setIcon(icon2)
        self.brectangle.setIconSize(QtCore.QSize(35, 35))
        self.brectangle.setObjectName("brectangle")
        self.gridLayout_2.addWidget(self.brectangle, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 2)
        self.bsetcolor = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsetcolor.sizePolicy().hasHeightForWidth())
        self.bsetcolor.setSizePolicy(sizePolicy)
        self.bsetcolor.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/palette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bsetcolor.setIcon(icon3)
        self.bsetcolor.setIconSize(QtCore.QSize(35, 35))
        self.bsetcolor.setObjectName("bsetcolor")
        self.gridLayout_2.addWidget(self.bsetcolor, 6, 1, 1, 1)
        self.blasso = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blasso.sizePolicy().hasHeightForWidth())
        self.blasso.setSizePolicy(sizePolicy)
        self.blasso.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/Lasso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blasso.setIcon(icon4)
        self.blasso.setIconSize(QtCore.QSize(35, 35))
        self.blasso.setObjectName("blasso")
        self.gridLayout_2.addWidget(self.blasso, 11, 0, 1, 1)
        self.bselectoron = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bselectoron.sizePolicy().hasHeightForWidth())
        self.bselectoron.setSizePolicy(sizePolicy)
        self.bselectoron.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/switch1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bselectoron.setIcon(icon5)
        self.bselectoron.setIconSize(QtCore.QSize(35, 35))
        self.bselectoron.setObjectName("bselectoron")
        self.gridLayout_2.addWidget(self.bselectoron, 8, 0, 1, 1)
        self.visionlabel = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.visionlabel.setFont(font)
        self.visionlabel.setTextFormat(QtCore.Qt.RichText)
        self.visionlabel.setObjectName("visionlabel")
        self.gridLayout_2.addWidget(self.visionlabel, 1, 0, 1, 1)
        self.bdswitch = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdswitch.sizePolicy().hasHeightForWidth())
        self.bdswitch.setSizePolicy(sizePolicy)
        self.bdswitch.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdswitch.setIcon(icon6)
        self.bdswitch.setIconSize(QtCore.QSize(35, 35))
        self.bdswitch.setObjectName("bdswitch")
        self.gridLayout_2.addWidget(self.bdswitch, 1, 1, 1, 1)
        self.bgrids = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgrids.sizePolicy().hasHeightForWidth())
        self.bgrids.setSizePolicy(sizePolicy)
        self.bgrids.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/grids1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bgrids.setIcon(icon7)
        self.bgrids.setIconSize(QtCore.QSize(35, 35))
        self.bgrids.setObjectName("bgrids")
        self.gridLayout_2.addWidget(self.bgrids, 4, 0, 1, 1)
        self.bchoosemark = QtWidgets.QPushButton(self.tab_3)
        self.bchoosemark.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/overlap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bchoosemark.setIcon(icon8)
        self.bchoosemark.setIconSize(QtCore.QSize(35, 35))
        self.bchoosemark.setObjectName("bchoosemark")
        self.gridLayout_2.addWidget(self.bchoosemark, 8, 1, 1, 1)
        self.artifactbox = QtWidgets.QComboBox(self.tab_3)
        self.artifactbox.setObjectName("artifactbox")
        self.artifactbox.addItem("")
        self.artifactbox.addItem("")
        self.artifactbox.addItem("")
        self.gridLayout_2.addWidget(self.artifactbox, 9, 0, 1, 2)
        self.linelabel = QtWidgets.QLabel(self.tab_3)
        self.linelabel.setObjectName("linelabel")
        self.gridLayout_2.addWidget(self.linelabel, 2, 0, 1, 1)
        self.columnbox = QtWidgets.QComboBox(self.tab_3)
        self.columnbox.setObjectName("columnbox")
        self.columnbox.addItem("")
        self.columnbox.addItem("")
        self.columnbox.addItem("")
        self.gridLayout_2.addWidget(self.columnbox, 3, 1, 1, 1)
        self.columnlabel = QtWidgets.QLabel(self.tab_3)
        self.columnlabel.setObjectName("columnlabel")
        self.gridLayout_2.addWidget(self.columnlabel, 3, 0, 1, 1)
        self.bellipse = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bellipse.sizePolicy().hasHeightForWidth())
        self.bellipse.setSizePolicy(sizePolicy)
        self.bellipse.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/Ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bellipse.setIcon(icon9)
        self.bellipse.setIconSize(QtCore.QSize(35, 35))
        self.bellipse.setObjectName("bellipse")
        self.gridLayout_2.addWidget(self.bellipse, 10, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.widget = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1115, 625))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 15)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.SpinBox_PatchX = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchX.setGeometry(QtCore.QRect(90, 241, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX.setFont(font)
        self.SpinBox_PatchX.setMaximum(500)
        self.SpinBox_PatchX.setProperty("value", 40)
        self.SpinBox_PatchX.setObjectName("SpinBox_PatchX")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(160, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.SpinBox_PatchY = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchY.setGeometry(QtCore.QRect(180, 240, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY.setFont(font)
        self.SpinBox_PatchY.setMaximum(500)
        self.SpinBox_PatchY.setProperty("value", 40)
        self.SpinBox_PatchY.setObjectName("SpinBox_PatchY")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(340, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.SpinBox_PatchOverlapp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.SpinBox_PatchOverlapp.setGeometry(QtCore.QRect(400, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp.setFont(font)
        self.SpinBox_PatchOverlapp.setMaximum(1.0)
        self.SpinBox_PatchOverlapp.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp.setObjectName("SpinBox_PatchOverlapp")
        self.Button_Patching = QtWidgets.QPushButton(self.groupBox)
        self.Button_Patching.setGeometry(QtCore.QRect(390, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching.setFont(font)
        self.Button_Patching.setObjectName("Button_Patching")
        self.TreeWidget_Patients = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Patients.setGeometry(QtCore.QRect(10, 78, 151, 151))
        self.TreeWidget_Patients.setObjectName("TreeWidget_Patients")
        self.TreeWidget_Patients.headerItem().setText(0, "1")
        self.TreeWidget_Datasets = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Datasets.setGeometry(QtCore.QRect(180, 78, 321, 151))
        self.TreeWidget_Datasets.setObjectName("TreeWidget_Datasets")
        self.TreeWidget_Datasets.headerItem().setText(0, "1")
        self.Button_DB = QtWidgets.QPushButton(self.groupBox)
        self.Button_DB.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB.setFont(font)
        self.Button_DB.setObjectName("Button_DB")
        self.Label_DB = QtWidgets.QLabel(self.groupBox)
        self.Label_DB.setGeometry(QtCore.QRect(130, 35, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB.setFont(font)
        self.Label_DB.setObjectName("Label_DB")
        self.Button_OutputPathPatching = QtWidgets.QPushButton(self.groupBox)
        self.Button_OutputPathPatching.setGeometry(QtCore.QRect(20, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching.setFont(font)
        self.Button_OutputPathPatching.setObjectName("Button_OutputPathPatching")
        self.Label_OutputPathPatching = QtWidgets.QLabel(self.groupBox)
        self.Label_OutputPathPatching.setGeometry(QtCore.QRect(130, 360, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching.setFont(font)
        self.Label_OutputPathPatching.setObjectName("Label_OutputPathPatching")
        self.Button_MarkingsPath = QtWidgets.QPushButton(self.groupBox)
        self.Button_MarkingsPath.setGeometry(QtCore.QRect(20, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_MarkingsPath.setFont(font)
        self.Button_MarkingsPath.setObjectName("Button_MarkingsPath")
        self.Label_MarkingsPath = QtWidgets.QLabel(self.groupBox)
        self.Label_MarkingsPath.setGeometry(QtCore.QRect(130, 320, 361, 31))
        self.Label_MarkingsPath.setObjectName("Label_MarkingsPath")
        self.RadioButton_MaskLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_MaskLabeling.setEnabled(True)
        self.RadioButton_MaskLabeling.setGeometry(QtCore.QRect(20, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_MaskLabeling.setFont(font)
        self.RadioButton_MaskLabeling.setChecked(True)
        self.RadioButton_MaskLabeling.setObjectName("RadioButton_MaskLabeling")
        self.RadioButton_PatchLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_PatchLabeling.setGeometry(QtCore.QRect(160, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_PatchLabeling.setFont(font)
        self.RadioButton_PatchLabeling.setObjectName("RadioButton_PatchLabeling")
        self.ComboBox_Patching = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_Patching.setGeometry(QtCore.QRect(330, 282, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComboBox_Patching.setFont(font)
        self.ComboBox_Patching.setObjectName("ComboBox_Patching")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.SpinBox_PatchZ = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchZ.setGeometry(QtCore.QRect(270, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchZ.setFont(font)
        self.SpinBox_PatchZ.setProperty("value", 5)
        self.SpinBox_PatchZ.setObjectName("SpinBox_PatchZ")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(250, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ComboBox_StoreOptions = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_StoreOptions.setGeometry(QtCore.QRect(20, 460, 151, 31))
        self.ComboBox_StoreOptions.setObjectName("ComboBox_StoreOptions")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_splittingMode = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_splittingMode.setGeometry(QtCore.QRect(20, 400, 171, 31))
        self.ComboBox_splittingMode.setObjectName("ComboBox_splittingMode")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.Label_SplittingParams = QtWidgets.QLabel(self.groupBox)
        self.Label_SplittingParams.setGeometry(QtCore.QRect(210, 405, 271, 21))
        self.Label_SplittingParams.setObjectName("Label_SplittingParams")
        self.CheckBox_SegmentationMask = QtWidgets.QCheckBox(self.groupBox)
        self.CheckBox_SegmentationMask.setGeometry(QtCore.QRect(190, 460, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_SegmentationMask.setFont(font)
        self.CheckBox_SegmentationMask.setObjectName("CheckBox_SegmentationMask")
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.Button_useCurrentData = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_useCurrentData.setEnabled(False)
        self.Button_useCurrentData.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.Button_useCurrentData.setObjectName("Button_useCurrentData")
        self.Button_selectDataset = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_selectDataset.setGeometry(QtCore.QRect(140, 30, 361, 31))
        self.Button_selectDataset.setObjectName("Button_selectDataset")
        self.Label_currentDataset = QtWidgets.QLabel(self.groupBox_4)
        self.Label_currentDataset.setGeometry(QtCore.QRect(10, 70, 491, 20))
        self.Label_currentDataset.setObjectName("Label_currentDataset")
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.GroupBox_TrainNN = QtWidgets.QGroupBox(self.tab_4)
        self.GroupBox_TrainNN.setEnabled(False)
        self.GroupBox_TrainNN.setObjectName("GroupBox_TrainNN")
        self.Button_LearningOutputPath = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_LearningOutputPath.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.Button_LearningOutputPath.setObjectName("Button_LearningOutputPath")
        self.Label_LearningOutputPath = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.Label_LearningOutputPath.setGeometry(QtCore.QRect(150, 75, 311, 21))
        self.Label_LearningOutputPath.setObjectName("Label_LearningOutputPath")
        self.Button_train = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_train.setGeometry(QtCore.QRect(280, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_train.setFont(font)
        self.Button_train.setObjectName("Button_train")
        self.ProgressBar_training = QtWidgets.QProgressBar(self.GroupBox_TrainNN)
        self.ProgressBar_training.setGeometry(QtCore.QRect(390, 540, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProgressBar_training.setFont(font)
        self.ProgressBar_training.setProperty("value", 100)
        self.ProgressBar_training.setObjectName("ProgressBar_training")
        self.ComboBox_DNNs = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_DNNs.setGeometry(QtCore.QRect(10, 20, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_DNNs.setFont(font)
        self.ComboBox_DNNs.setObjectName("ComboBox_DNNs")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 200, 281, 106))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.DoubleSpinBox_WeightDecay = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_WeightDecay.setFont(font)
        self.DoubleSpinBox_WeightDecay.setDecimals(5)
        self.DoubleSpinBox_WeightDecay.setMaximum(1.0)
        self.DoubleSpinBox_WeightDecay.setSingleStep(0.0001)
        self.DoubleSpinBox_WeightDecay.setProperty("value", 0.0001)
        self.DoubleSpinBox_WeightDecay.setObjectName("DoubleSpinBox_WeightDecay")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DoubleSpinBox_WeightDecay)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.DoubleSpinBox_Momentum = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_Momentum.setFont(font)
        self.DoubleSpinBox_Momentum.setMaximum(1.0)
        self.DoubleSpinBox_Momentum.setSingleStep(0.05)
        self.DoubleSpinBox_Momentum.setProperty("value", 0.9)
        self.DoubleSpinBox_Momentum.setObjectName("DoubleSpinBox_Momentum")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DoubleSpinBox_Momentum)
        self.CheckBox_Nesterov = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Nesterov.setFont(font)
        self.CheckBox_Nesterov.setObjectName("CheckBox_Nesterov")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CheckBox_Nesterov)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 515, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CheckBox_Artifacts = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Artifacts.setFont(font)
        self.CheckBox_Artifacts.setObjectName("CheckBox_Artifacts")
        self.horizontalLayout.addWidget(self.CheckBox_Artifacts)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CheckBox_BodyRegion = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_BodyRegion.setFont(font)
        self.CheckBox_BodyRegion.setObjectName("CheckBox_BodyRegion")
        self.horizontalLayout.addWidget(self.CheckBox_BodyRegion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CheckBox_TWeighting = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_TWeighting.setFont(font)
        self.CheckBox_TWeighting.setObjectName("CheckBox_TWeighting")
        self.horizontalLayout.addWidget(self.CheckBox_TWeighting)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 594, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CheckBox_DataAugmentation = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CheckBox_DataAugmentation.setFont(font)
        self.CheckBox_DataAugmentation.setObjectName("CheckBox_DataAugmentation")
        self.verticalLayout.addWidget(self.CheckBox_DataAugmentation)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBox_DataAug_horizontalFlip = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_horizontalFlip.setFont(font)
        self.CheckBox_DataAug_horizontalFlip.setObjectName("CheckBox_DataAug_horizontalFlip")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_horizontalFlip)
        self.CheckBox_DataAug_verticalFlip = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_verticalFlip.setFont(font)
        self.CheckBox_DataAug_verticalFlip.setObjectName("CheckBox_DataAug_verticalFlip")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_verticalFlip)
        self.CheckBox_DataAug_Rotation = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_Rotation.setFont(font)
        self.CheckBox_DataAug_Rotation.setObjectName("CheckBox_DataAug_Rotation")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_Rotation)
        self.CheckBox_DataAug_Zoom = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.CheckBox_DataAug_Zoom.setObjectName("CheckBox_DataAug_Zoom")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_Zoom)
        self.CheckBox_DataAug_zcaWeighting = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_zcaWeighting.setFont(font)
        self.CheckBox_DataAug_zcaWeighting.setObjectName("CheckBox_DataAug_zcaWeighting")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_zcaWeighting)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBox_DataAug_HeightShift = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_HeightShift.setFont(font)
        self.CheckBox_DataAug_HeightShift.setObjectName("CheckBox_DataAug_HeightShift")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_HeightShift)
        self.CheckBox_DataAug_WidthShift = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_WidthShift.setFont(font)
        self.CheckBox_DataAug_WidthShift.setObjectName("CheckBox_DataAug_WidthShift")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_WidthShift)
        self.RadioButton_DataAug_contrastStretching = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_contrastStretching.setObjectName("RadioButton_DataAug_contrastStretching")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_contrastStretching)
        self.RadioButton_DataAug_histogramEq = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_histogramEq.setObjectName("RadioButton_DataAug_histogramEq")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_histogramEq)
        self.RadioButton_DataAug_adaptiveEq = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_adaptiveEq.setObjectName("RadioButton_DataAug_adaptiveEq")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_adaptiveEq)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.LineEdit_LearningRates = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_LearningRates.setGeometry(QtCore.QRect(250, 121, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_LearningRates.setFont(font)
        self.LineEdit_LearningRates.setObjectName("LineEdit_LearningRates")
        self.label_3 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ComboBox_Optimizers = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_Optimizers.setGeometry(QtCore.QRect(150, 150, 221, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_Optimizers.setFont(font)
        self.ComboBox_Optimizers.setObjectName("ComboBox_Optimizers")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.LineEdit_BatchSizes = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_BatchSizes.setGeometry(QtCore.QRect(500, 120, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_BatchSizes.setFont(font)
        self.LineEdit_BatchSizes.setObjectName("LineEdit_BatchSizes")
        self.label_2 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_2.setGeometry(QtCore.QRect(400, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_8.setGeometry(QtCore.QRect(400, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.SpinBox_Epochs = QtWidgets.QSpinBox(self.GroupBox_TrainNN)
        self.SpinBox_Epochs.setGeometry(QtCore.QRect(500, 150, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_Epochs.setFont(font)
        self.SpinBox_Epochs.setMaximum(100000)
        self.SpinBox_Epochs.setProperty("value", 100)
        self.SpinBox_Epochs.setObjectName("SpinBox_Epochs")
        self.ComboBox_GPU = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_GPU.setGeometry(QtCore.QRect(70, 540, 61, 31))
        self.ComboBox_GPU.setObjectName("ComboBox_GPU")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.label_15 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_15.setGeometry(QtCore.QRect(10, 540, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.GroupBox_TrainNN)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 60, 151, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 20, 151, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 191, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.wy2 = QtWidgets.QPushButton(self.groupBox_2)
        self.wy2.setGeometry(QtCore.QRect(20, 20, 151, 21))
        self.wy2.setObjectName("wy2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 230, 191, 211))
        self.groupBox_8.setObjectName("groupBox_8")
        self.wy3 = QtWidgets.QPushButton(self.groupBox_8)
        self.wy3.setGeometry(QtCore.QRect(20, 20, 151, 23))
        self.wy3.setObjectName("wy3")
        self.listView_2 = QtWidgets.QListView(self.groupBox_8)
        self.listView_2.setGeometry(QtCore.QRect(20, 50, 151, 121))
        self.listView_2.setObjectName("listView_2")
        self.wy4 = QtWidgets.QPushButton(self.groupBox_8)
        self.wy4.setGeometry(QtCore.QRect(20, 180, 151, 23))
        self.wy4.setObjectName("wy4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 460, 191, 51))
        self.groupBox_9.setObjectName("groupBox_9")
        self.wy5 = QtWidgets.QPushButton(self.groupBox_9)
        self.wy5.setGeometry(QtCore.QRect(20, 20, 151, 23))
        self.wy5.setObjectName("wy5")
        self.matplotlibwidget_static = MatplotlibWidget(self.groupBox_5)
        self.matplotlibwidget_static.setGeometry(QtCore.QRect(540, 20, 301, 581))
        self.matplotlibwidget_static.setObjectName("matplotlibwidget_static")
        self.matplotlibwidget_static_2 = MatplotlibWidget(self.matplotlibwidget_static)
        self.matplotlibwidget_static_2.setGeometry(QtCore.QRect(-270, 10, 961, 591))
        self.matplotlibwidget_static_2.setObjectName("matplotlibwidget_static_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(320, 540, 531, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_3.setGeometry(QtCore.QRect(890, 540, 71, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.matplotlibwidget_static_3 = MatplotlibWidget(self.groupBox_5)
        self.matplotlibwidget_static_3.setGeometry(QtCore.QRect(350, 10, 741, 571))
        self.matplotlibwidget_static_3.setObjectName("matplotlibwidget_static_3")
        self.wyh5 = QtWidgets.QPushButton(self.groupBox_5)
        self.wyh5.setGeometry(QtCore.QRect(40, 30, 101, 21))
        self.wyh5.setObjectName("wyh5")
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1319, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionColor = QtWidgets.QAction(MainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuSetting.addAction(self.actionColor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.linebox.setItemText(0, _translate("MainWindow", "1"))
        self.linebox.setItemText(1, _translate("MainWindow", "2"))
        self.linebox.setItemText(2, _translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "result"))
        self.label_5.setText(_translate("MainWindow", "image"))
        self.label_4.setText(_translate("MainWindow", "label"))
        self.visionlabel.setText(_translate("MainWindow", "2D"))
        self.artifactbox.setItemText(0, _translate("MainWindow", "move"))
        self.artifactbox.setItemText(1, _translate("MainWindow", "shim"))
        self.artifactbox.setItemText(2, _translate("MainWindow", "noise"))
        self.linelabel.setText(_translate("MainWindow", "line"))
        self.columnbox.setItemText(0, _translate("MainWindow", "1"))
        self.columnbox.setItemText(1, _translate("MainWindow", "2"))
        self.columnbox.setItemText(2, _translate("MainWindow", "3"))
        self.columnlabel.setText(_translate("MainWindow", "column"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Data Viewing"))
        self.groupBox.setTitle(_translate("MainWindow", "Database and Patching"))
        self.label_7.setText(_translate("MainWindow", "x"))
        self.label_9.setText(_translate("MainWindow", "Patch Size:"))
        self.label_10.setText(_translate("MainWindow", "Overlap:"))
        self.Button_Patching.setText(_translate("MainWindow", "Perform Patching"))
        self.Button_DB.setText(_translate("MainWindow", "Select Database"))
        self.Label_DB.setText(_translate("MainWindow", "No Database selected"))
        self.Button_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.Label_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.Button_MarkingsPath.setText(_translate("MainWindow", "Markings Path"))
        self.Label_MarkingsPath.setText(_translate("MainWindow", "Markings Path"))
        self.RadioButton_MaskLabeling.setText(_translate("MainWindow", "Mask Labeling"))
        self.RadioButton_PatchLabeling.setText(_translate("MainWindow", "Patch Labeling"))
        self.ComboBox_Patching.setItemText(0, _translate("MainWindow", "Select Patching Mode ..."))
        self.ComboBox_Patching.setItemText(1, _translate("MainWindow", "2D"))
        self.ComboBox_Patching.setItemText(2, _translate("MainWindow", "3D"))
        self.label_11.setText(_translate("MainWindow", "x"))
        self.ComboBox_StoreOptions.setItemText(0, _translate("MainWindow", "Do not store on HD"))
        self.ComboBox_StoreOptions.setItemText(1, _translate("MainWindow", "H5PY"))
        self.ComboBox_StoreOptions.setItemText(2, _translate("MainWindow", "Patch based"))
        self.ComboBox_splittingMode.setItemText(0, _translate("MainWindow", "Select Data Spliting ..."))
        self.ComboBox_splittingMode.setItemText(1, _translate("MainWindow", "Simple Random Samples"))
        self.ComboBox_splittingMode.setItemText(2, _translate("MainWindow", "Crossvalidation"))
        self.ComboBox_splittingMode.setItemText(3, _translate("MainWindow", "Patient Crossvalidation"))
        self.Label_SplittingParams.setText(_translate("MainWindow", "Splitting Params"))
        self.CheckBox_SegmentationMask.setText(_translate("MainWindow", "Using Segmentation Masks"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dataset for Deep Learning"))
        self.Button_useCurrentData.setText(_translate("MainWindow", "Use current data"))
        self.Button_selectDataset.setText(_translate("MainWindow", "Select Dataset"))
        self.Label_currentDataset.setText(_translate("MainWindow", "No Dataset is selected for Deep Learning!"))
        self.GroupBox_TrainNN.setTitle(_translate("MainWindow", "Train Deep Neural Network"))
        self.Button_LearningOutputPath.setText(_translate("MainWindow", "Learning Output Path"))
        self.Label_LearningOutputPath.setText(_translate("MainWindow", "Select Network Output Path!"))
        self.Button_train.setText(_translate("MainWindow", "Train"))
        self.label_13.setText(_translate("MainWindow", "Momentum:"))
        self.CheckBox_Nesterov.setText(_translate("MainWindow", "Nesterov"))
        self.label_14.setText(_translate("MainWindow", "Weight Decay:"))
        self.label.setText(_translate("MainWindow", "Select Multiclasses:"))
        self.CheckBox_Artifacts.setText(_translate("MainWindow", "Artifacts"))
        self.CheckBox_BodyRegion.setText(_translate("MainWindow", "Body Region"))
        self.CheckBox_TWeighting.setText(_translate("MainWindow", "T Weighting"))
        self.CheckBox_DataAugmentation.setText(_translate("MainWindow", "Data Augmentation"))
        self.CheckBox_DataAug_horizontalFlip.setText(_translate("MainWindow", "Horizontal Flip"))
        self.CheckBox_DataAug_verticalFlip.setText(_translate("MainWindow", "Vertical Flip"))
        self.CheckBox_DataAug_Rotation.setText(_translate("MainWindow", "Rotation"))
        self.CheckBox_DataAug_Zoom.setText(_translate("MainWindow", "Zoom"))
        self.CheckBox_DataAug_zcaWeighting.setText(_translate("MainWindow", "ZCA Whitening"))
        self.CheckBox_DataAug_HeightShift.setText(_translate("MainWindow", "Height Shift"))
        self.CheckBox_DataAug_WidthShift.setText(_translate("MainWindow", "Width Shift"))
        self.RadioButton_DataAug_contrastStretching.setText(_translate("MainWindow", "Contrast Stretching"))
        self.RadioButton_DataAug_histogramEq.setText(_translate("MainWindow", "Histogram Eq"))
        self.RadioButton_DataAug_adaptiveEq.setText(_translate("MainWindow", "Adaptive Eq"))
        self.LineEdit_LearningRates.setText(_translate("MainWindow", "0.1,0.01,0.001"))
        self.label_3.setText(_translate("MainWindow", "Learning Rates \"0.1,0.01,0.005\" :"))
        self.label_12.setText(_translate("MainWindow", "Optimizer:"))
        self.ComboBox_Optimizers.setItemText(0, _translate("MainWindow", "SGD"))
        self.ComboBox_Optimizers.setItemText(1, _translate("MainWindow", "RMSprop"))
        self.ComboBox_Optimizers.setItemText(2, _translate("MainWindow", "Adagrad"))
        self.ComboBox_Optimizers.setItemText(3, _translate("MainWindow", "Adadelta"))
        self.ComboBox_Optimizers.setItemText(4, _translate("MainWindow", "Adam"))
        self.LineEdit_BatchSizes.setText(_translate("MainWindow", "128"))
        self.label_2.setText(_translate("MainWindow", "Batch Size/s:"))
        self.label_8.setText(_translate("MainWindow", "Epochs:"))
        self.ComboBox_GPU.setItemText(0, _translate("MainWindow", "1"))
        self.ComboBox_GPU.setItemText(1, _translate("MainWindow", "2"))
        self.ComboBox_GPU.setItemText(2, _translate("MainWindow", "3"))
        self.ComboBox_GPU.setItemText(3, _translate("MainWindow", "4"))
        self.label_15.setText(_translate("MainWindow", "GPU:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results and Prediction"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Network Training"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Choose one H5 file"))
        self.groupBox_7.setTitle(_translate("MainWindow", "The chosen file"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Visualization of Weights"))
        self.wy2.setText(_translate("MainWindow", "Show the Weights"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Visualization of Architecture"))
        self.wy3.setText(_translate("MainWindow", "Show the Layers\' Names"))
        self.wy4.setText(_translate("MainWindow", "Show the Plot"))
        self.groupBox_9.setTitle(_translate("MainWindow", "DeepVisualization"))
        self.wy5.setText(_translate("MainWindow", "Show Subset Selection"))
        self.wyh5.setText(_translate("MainWindow", "choose the file"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Network Visualization"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionSave.setText(_translate("MainWindow", "Save current"))
        self.actionColor.setText(_translate("MainWindow", "Colors"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))

from matplotlibwidget import MatplotlibWidget
import resrc_rc
