# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framework1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1550, 998)
        MainWindow.setAcceptDrops(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 1521, 921))
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 137, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout111 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout111.setContentsMargins(0, 0, 0, 0)
        self.layout111.setObjectName("layout111")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setObjectName("label_5")
        self.layout111.addWidget(self.label_5)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 121, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.combo_layline = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_layline.setObjectName("combo_layline")
        self.combo_layline.addItem("")
        self.combo_layline.addItem("")
        self.combo_layline.addItem("")
        self.gridLayout.addWidget(self.combo_layline, 0, 1, 1, 1)
        self.combo_laycolumn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_laycolumn.setObjectName("combo_laycolumn")
        self.combo_laycolumn.addItem("")
        self.combo_laycolumn.addItem("")
        self.combo_laycolumn.addItem("")
        self.gridLayout.addWidget(self.combo_laycolumn, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.grids1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.grids1.setObjectName("grids1")
        self.gridLayout.addWidget(self.grids1, 2, 0, 2, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 121, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.combo_3D = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.combo_3D.setObjectName("combo_3D")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.combo_3D.addItem("")
        self.gridLayout_2.addWidget(self.combo_3D, 0, 1, 1, 1)
        self.grids2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.grids2.setObjectName("grids2")
        self.gridLayout_2.addWidget(self.grids2, 2, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.layout111.addWidget(self.tabWidget)
        self.openfile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openfile.setObjectName("openfile")
        self.layout111.addWidget(self.openfile)
        self.resetdicom = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetdicom.setObjectName("resetdicom")
        self.layout111.addWidget(self.resetdicom)
        self.clearimage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearimage.setObjectName("clearimage")
        self.layout111.addWidget(self.clearimage)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layout111.addWidget(self.line_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setObjectName("label_6")
        self.layout111.addWidget(self.label_6)
        self.bpatch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bpatch.setObjectName("bpatch")
        self.layout111.addWidget(self.bpatch)
        self.resultpatch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resultpatch.setObjectName("resultpatch")
        self.layout111.addWidget(self.resultpatch)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layout111.addWidget(self.line_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setObjectName("label_4")
        self.layout111.addWidget(self.label_4)
        self.bselectoron = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bselectoron.setObjectName("bselectoron")
        self.layout111.addWidget(self.bselectoron)
        self.artefactbox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.artefactbox.setObjectName("artefactbox")
        self.artefactbox.addItem("")
        self.artefactbox.addItem("")
        self.artefactbox.addItem("")
        self.layout111.addWidget(self.artefactbox)
        self.bnoselect = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.bnoselect.setObjectName("bnoselect")
        self.layout111.addWidget(self.bnoselect)
        self.brectangle = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.brectangle.setObjectName("brectangle")
        self.layout111.addWidget(self.brectangle)
        self.bellipse = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.bellipse.setObjectName("bellipse")
        self.layout111.addWidget(self.bellipse)
        self.blasso = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.blasso.setObjectName("blasso")
        self.layout111.addWidget(self.blasso)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.layout111.addWidget(self.line_6)
        self.exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.layout111.addWidget(self.exit)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(160, 10, 1351, 881))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1349, 879))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 511, 501))
        self.groupBox.setObjectName("groupBox")
        self.SpinBox_PatchX = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchX.setGeometry(QtCore.QRect(90, 241, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX.setFont(font)
        self.SpinBox_PatchX.setMaximum(500)
        self.SpinBox_PatchX.setProperty("value", 40)
        self.SpinBox_PatchX.setObjectName("SpinBox_PatchX")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(160, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.SpinBox_PatchY = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchY.setGeometry(QtCore.QRect(180, 240, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY.setFont(font)
        self.SpinBox_PatchY.setMaximum(500)
        self.SpinBox_PatchY.setProperty("value", 40)
        self.SpinBox_PatchY.setObjectName("SpinBox_PatchY")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(340, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.SpinBox_PatchOverlapp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.SpinBox_PatchOverlapp.setGeometry(QtCore.QRect(400, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp.setFont(font)
        self.SpinBox_PatchOverlapp.setMaximum(1.0)
        self.SpinBox_PatchOverlapp.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp.setObjectName("SpinBox_PatchOverlapp")
        self.Button_Patching = QtWidgets.QPushButton(self.groupBox)
        self.Button_Patching.setGeometry(QtCore.QRect(370, 450, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching.setFont(font)
        self.Button_Patching.setObjectName("Button_Patching")
        self.TreeWidget_Patients = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Patients.setGeometry(QtCore.QRect(10, 78, 151, 151))
        self.TreeWidget_Patients.setObjectName("TreeWidget_Patients")
        self.TreeWidget_Patients.headerItem().setText(0, "1")
        self.TreeWidget_Datasets = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Datasets.setGeometry(QtCore.QRect(180, 78, 321, 151))
        self.TreeWidget_Datasets.setObjectName("TreeWidget_Datasets")
        self.TreeWidget_Datasets.headerItem().setText(0, "1")
        self.Button_DB = QtWidgets.QPushButton(self.groupBox)
        self.Button_DB.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB.setFont(font)
        self.Button_DB.setObjectName("Button_DB")
        self.Label_DB = QtWidgets.QLabel(self.groupBox)
        self.Label_DB.setGeometry(QtCore.QRect(130, 35, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB.setFont(font)
        self.Label_DB.setObjectName("Label_DB")
        self.Button_OutputPathPatching = QtWidgets.QPushButton(self.groupBox)
        self.Button_OutputPathPatching.setGeometry(QtCore.QRect(20, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching.setFont(font)
        self.Button_OutputPathPatching.setObjectName("Button_OutputPathPatching")
        self.Label_OutputPathPatching = QtWidgets.QLabel(self.groupBox)
        self.Label_OutputPathPatching.setGeometry(QtCore.QRect(130, 360, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching.setFont(font)
        self.Label_OutputPathPatching.setObjectName("Label_OutputPathPatching")
        self.Button_MarkingsPath = QtWidgets.QPushButton(self.groupBox)
        self.Button_MarkingsPath.setGeometry(QtCore.QRect(20, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_MarkingsPath.setFont(font)
        self.Button_MarkingsPath.setObjectName("Button_MarkingsPath")
        self.Label_MarkingsPath = QtWidgets.QLabel(self.groupBox)
        self.Label_MarkingsPath.setGeometry(QtCore.QRect(130, 320, 361, 31))
        self.Label_MarkingsPath.setObjectName("Label_MarkingsPath")
        self.RadioButton_MaskLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_MaskLabeling.setEnabled(True)
        self.RadioButton_MaskLabeling.setGeometry(QtCore.QRect(20, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_MaskLabeling.setFont(font)
        self.RadioButton_MaskLabeling.setChecked(True)
        self.RadioButton_MaskLabeling.setObjectName("RadioButton_MaskLabeling")
        self.RadioButton_PatchLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_PatchLabeling.setGeometry(QtCore.QRect(160, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_PatchLabeling.setFont(font)
        self.RadioButton_PatchLabeling.setObjectName("RadioButton_PatchLabeling")
        self.ComboBox_Patching = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_Patching.setGeometry(QtCore.QRect(330, 282, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComboBox_Patching.setFont(font)
        self.ComboBox_Patching.setObjectName("ComboBox_Patching")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.SpinBox_PatchZ = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchZ.setGeometry(QtCore.QRect(270, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchZ.setFont(font)
        self.SpinBox_PatchZ.setProperty("value", 5)
        self.SpinBox_PatchZ.setObjectName("SpinBox_PatchZ")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(250, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ComboBox_StoreOptions = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_StoreOptions.setGeometry(QtCore.QRect(20, 450, 151, 31))
        self.ComboBox_StoreOptions.setObjectName("ComboBox_StoreOptions")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_splittingMode = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_splittingMode.setGeometry(QtCore.QRect(20, 400, 171, 31))
        self.ComboBox_splittingMode.setObjectName("ComboBox_splittingMode")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.Label_SplittingParams = QtWidgets.QLabel(self.groupBox)
        self.Label_SplittingParams.setGeometry(QtCore.QRect(210, 405, 271, 21))
        self.Label_SplittingParams.setObjectName("Label_SplittingParams")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 20, 491, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.GroupBox_TrainNN = QtWidgets.QGroupBox(self.tab_4)
        self.GroupBox_TrainNN.setEnabled(False)
        self.GroupBox_TrainNN.setGeometry(QtCore.QRect(530, 360, 501, 351))
        self.GroupBox_TrainNN.setObjectName("GroupBox_TrainNN")
        self.Button_LearningOutputPath = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_LearningOutputPath.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.Button_LearningOutputPath.setObjectName("Button_LearningOutputPath")
        self.Label_LearningOutputPath = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.Label_LearningOutputPath.setGeometry(QtCore.QRect(150, 75, 311, 21))
        self.Label_LearningOutputPath.setObjectName("Label_LearningOutputPath")
        self.label_11 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_11.setGeometry(QtCore.QRect(10, 109, 81, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 231, 31))
        self.label_12.setObjectName("label_12")
        self.LineEdit_LearningRates = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_LearningRates.setGeometry(QtCore.QRect(240, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_LearningRates.setFont(font)
        self.LineEdit_LearningRates.setObjectName("LineEdit_LearningRates")
        self.label_13 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_13.setGeometry(QtCore.QRect(300, 110, 55, 31))
        self.label_13.setObjectName("label_13")
        self.SpinBox_Epochs = QtWidgets.QSpinBox(self.GroupBox_TrainNN)
        self.SpinBox_Epochs.setGeometry(QtCore.QRect(360, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_Epochs.setFont(font)
        self.SpinBox_Epochs.setMaximum(100000)
        self.SpinBox_Epochs.setProperty("value", 100)
        self.SpinBox_Epochs.setObjectName("SpinBox_Epochs")
        self.Button_train = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_train.setGeometry(QtCore.QRect(200, 280, 101, 41))
        self.Button_train.setObjectName("Button_train")
        self.ProgressBar_training = QtWidgets.QProgressBar(self.GroupBox_TrainNN)
        self.ProgressBar_training.setGeometry(QtCore.QRect(310, 290, 151, 21))
        self.ProgressBar_training.setProperty("value", 100)
        self.ProgressBar_training.setObjectName("ProgressBar_training")
        self.ComboBox_DNNs = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_DNNs.setGeometry(QtCore.QRect(10, 20, 451, 31))
        self.ComboBox_DNNs.setObjectName("ComboBox_DNNs")
        self.CheckBox_Artifacts = QtWidgets.QCheckBox(self.GroupBox_TrainNN)
        self.CheckBox_Artifacts.setGeometry(QtCore.QRect(14, 230, 91, 31))
        self.CheckBox_Artifacts.setObjectName("CheckBox_Artifacts")
        self.label_14 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_14.setGeometry(QtCore.QRect(10, 210, 451, 21))
        self.label_14.setObjectName("label_14")
        self.CheckBox_BodyRegion = QtWidgets.QCheckBox(self.GroupBox_TrainNN)
        self.CheckBox_BodyRegion.setGeometry(QtCore.QRect(120, 230, 111, 31))
        self.CheckBox_BodyRegion.setObjectName("CheckBox_BodyRegion")
        self.CheckBox_TWeighting = QtWidgets.QCheckBox(self.GroupBox_TrainNN)
        self.CheckBox_TWeighting.setGeometry(QtCore.QRect(250, 230, 141, 31))
        self.CheckBox_TWeighting.setObjectName("CheckBox_TWeighting")
        self.LineEdit_BatchSizes = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_BatchSizes.setGeometry(QtCore.QRect(100, 110, 171, 31))
        self.LineEdit_BatchSizes.setObjectName("LineEdit_BatchSizes")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 530, 511, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.Button_useCurrentData = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_useCurrentData.setEnabled(False)
        self.Button_useCurrentData.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.Button_useCurrentData.setObjectName("Button_useCurrentData")
        self.Button_selectDataset = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_selectDataset.setGeometry(QtCore.QRect(140, 30, 361, 31))
        self.Button_selectDataset.setObjectName("Button_selectDataset")
        self.Label_currentDataset = QtWidgets.QLabel(self.groupBox_4)
        self.Label_currentDataset.setGeometry(QtCore.QRect(10, 70, 491, 20))
        self.Label_currentDataset.setObjectName("Label_currentDataset")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1550, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "image"))
        self.label.setText(_translate("MainWindow", "lines"))
        self.combo_layline.setItemText(0, _translate("MainWindow", "1"))
        self.combo_layline.setItemText(1, _translate("MainWindow", "2"))
        self.combo_layline.setItemText(2, _translate("MainWindow", "3"))
        self.combo_laycolumn.setItemText(0, _translate("MainWindow", "1"))
        self.combo_laycolumn.setItemText(1, _translate("MainWindow", "2"))
        self.combo_laycolumn.setItemText(2, _translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "columns"))
        self.grids1.setText(_translate("MainWindow", "make grids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "2D"))
        self.label_3.setText(_translate("MainWindow", "lines"))
        self.combo_3D.setItemText(0, _translate("MainWindow", "1"))
        self.combo_3D.setItemText(1, _translate("MainWindow", "2"))
        self.combo_3D.setItemText(2, _translate("MainWindow", "3"))
        self.combo_3D.setItemText(3, _translate("MainWindow", "4"))
        self.combo_3D.setItemText(4, _translate("MainWindow", "5"))
        self.combo_3D.setItemText(5, _translate("MainWindow", "6"))
        self.combo_3D.setItemText(6, _translate("MainWindow", "7"))
        self.combo_3D.setItemText(7, _translate("MainWindow", "8"))
        self.grids2.setText(_translate("MainWindow", "make grids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3D"))
        self.openfile.setText(_translate("MainWindow", " load image"))
        self.resetdicom.setText(_translate("MainWindow", "reset"))
        self.clearimage.setText(_translate("MainWindow", "clear"))
        self.label_6.setText(_translate("MainWindow", "result"))
        self.bpatch.setText(_translate("MainWindow", "load result patches"))
        self.resultpatch.setText(_translate("MainWindow", "view result"))
        self.label_4.setText(_translate("MainWindow", "artefact"))
        self.bselectoron.setText(_translate("MainWindow", "selector on/off"))
        self.artefactbox.setItemText(0, _translate("MainWindow", "movement"))
        self.artefactbox.setItemText(1, _translate("MainWindow", "shim"))
        self.artefactbox.setItemText(2, _translate("MainWindow", "noise"))
        self.bnoselect.setText(_translate("MainWindow", "no selector"))
        self.brectangle.setText(_translate("MainWindow", "rectangle"))
        self.bellipse.setText(_translate("MainWindow", "ellipse"))
        self.blasso.setText(_translate("MainWindow", "lasso"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "DICOM"))
        self.groupBox.setTitle(_translate("MainWindow", "Database and Patching"))
        self.label_7.setText(_translate("MainWindow", "x"))
        self.label_8.setText(_translate("MainWindow", "Patch Size:"))
        self.label_9.setText(_translate("MainWindow", "Overlap:"))
        self.Button_Patching.setText(_translate("MainWindow", "Perform Patching"))
        self.Button_DB.setText(_translate("MainWindow", "Select Database"))
        self.Label_DB.setText(_translate("MainWindow", "No Database selected"))
        self.Button_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.Label_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.Button_MarkingsPath.setText(_translate("MainWindow", "Markings Path"))
        self.Label_MarkingsPath.setText(_translate("MainWindow", "Markings Path"))
        self.RadioButton_MaskLabeling.setText(_translate("MainWindow", "Mask Labeling"))
        self.RadioButton_PatchLabeling.setText(_translate("MainWindow", "Patch Labeling"))
        self.ComboBox_Patching.setItemText(0, _translate("MainWindow", "Select Patching Mode ..."))
        self.ComboBox_Patching.setItemText(1, _translate("MainWindow", "2D"))
        self.ComboBox_Patching.setItemText(2, _translate("MainWindow", "3D"))
        self.label_10.setText(_translate("MainWindow", "x"))
        self.ComboBox_StoreOptions.setItemText(0, _translate("MainWindow", "Do not store on HD"))
        self.ComboBox_StoreOptions.setItemText(1, _translate("MainWindow", "H5PY"))
        self.ComboBox_StoreOptions.setItemText(2, _translate("MainWindow", "Patch based"))
        self.ComboBox_splittingMode.setItemText(0, _translate("MainWindow", "Select Data Spliting ..."))
        self.ComboBox_splittingMode.setItemText(1, _translate("MainWindow", "Simple Random Samples"))
        self.ComboBox_splittingMode.setItemText(2, _translate("MainWindow", "Crossvalidation"))
        self.ComboBox_splittingMode.setItemText(3, _translate("MainWindow", "Patient Crossvalidation"))
        self.Label_SplittingParams.setText(_translate("MainWindow", "Splitting Params"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Training Parameters"))
        self.GroupBox_TrainNN.setTitle(_translate("MainWindow", "Train Deep Neural Network"))
        self.Button_LearningOutputPath.setText(_translate("MainWindow", "Learning Output Path"))
        self.Label_LearningOutputPath.setText(_translate("MainWindow", "Select Network Output Path!"))
        self.label_11.setText(_translate("MainWindow", "Batch Size/s:"))
        self.label_12.setText(_translate("MainWindow", "Learning Rates \"0.1,0.01,0.005\" :"))
        self.LineEdit_LearningRates.setText(_translate("MainWindow", "0.1,0.01,0.005,0.001"))
        self.label_13.setText(_translate("MainWindow", "Epochs:"))
        self.Button_train.setText(_translate("MainWindow", "Train"))
        self.CheckBox_Artifacts.setText(_translate("MainWindow", "Artifacts"))
        self.label_14.setText(_translate("MainWindow", "Select Classes for Multiclass Classification:"))
        self.CheckBox_BodyRegion.setText(_translate("MainWindow", "Body Region"))
        self.CheckBox_TWeighting.setText(_translate("MainWindow", "T Weighting"))
        self.LineEdit_BatchSizes.setText(_translate("MainWindow", "128"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dataset for Deep Learning"))
        self.Button_useCurrentData.setText(_translate("MainWindow", "Use current data"))
        self.Button_selectDataset.setText(_translate("MainWindow", "Select Dataset"))
        self.Label_currentDataset.setText(_translate("MainWindow", "No Dataset is selected for Deep Learning!"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "train"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "view network"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "metrics"))

