# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framework.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 813)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/research.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.DataViewing = QtWidgets.QWidget()
        self.DataViewing.setObjectName("DataViewing")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.DataViewing)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.DataViewing)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 8, 1, 1, 2)
        self.labelResult = QtWidgets.QLabel(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelResult.sizePolicy().hasHeightForWidth())
        self.labelResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelResult.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelResult.setObjectName("labelResult")
        self.gridLayout_2.addWidget(self.labelResult, 2, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.bnoselect = QtWidgets.QRadioButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnoselect.sizePolicy().hasHeightForWidth())
        self.bnoselect.setSizePolicy(sizePolicy)
        self.bnoselect.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bnoselect.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bnoselect.setIcon(icon1)
        self.bnoselect.setObjectName("bnoselect")
        self.gridLayout_2.addWidget(self.bnoselect, 10, 2, 1, 1)
        self.bselectoron = QtWidgets.QPushButton(self.DataViewing)
        self.bselectoron.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bselectoron.sizePolicy().hasHeightForWidth())
        self.bselectoron.setSizePolicy(sizePolicy)
        self.bselectoron.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/switchoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bselectoron.setIcon(icon2)
        self.bselectoron.setIconSize(QtCore.QSize(35, 35))
        self.bselectoron.setObjectName("bselectoron")
        self.gridLayout_2.addWidget(self.bselectoron, 10, 1, 1, 1)
        self.blasso = QtWidgets.QRadioButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blasso.sizePolicy().hasHeightForWidth())
        self.blasso.setSizePolicy(sizePolicy)
        self.blasso.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/lasso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blasso.setIcon(icon3)
        self.blasso.setIconSize(QtCore.QSize(35, 35))
        self.blasso.setObjectName("blasso")
        self.gridLayout_2.addWidget(self.blasso, 12, 2, 1, 1)
        self.deleteButton = QtWidgets.QToolButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setAutoFillBackground(True)
        self.deleteButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon4)
        self.deleteButton.setIconSize(QtCore.QSize(35, 35))
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_2.addWidget(self.deleteButton, 15, 1, 1, 1)
        self.infoButton = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoButton.sizePolicy().hasHeightForWidth())
        self.infoButton.setSizePolicy(sizePolicy)
        self.infoButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon5)
        self.infoButton.setIconSize(QtCore.QSize(35, 35))
        self.infoButton.setObjectName("infoButton")
        self.gridLayout_2.addWidget(self.infoButton, 1, 1, 1, 1)
        self.cursorCross = QtWidgets.QCheckBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursorCross.sizePolicy().hasHeightForWidth())
        self.cursorCross.setSizePolicy(sizePolicy)
        self.cursorCross.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/cursor cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cursorCross.setIcon(icon6)
        self.cursorCross.setIconSize(QtCore.QSize(35, 35))
        self.cursorCross.setObjectName("cursorCross")
        self.gridLayout_2.addWidget(self.cursorCross, 11, 1, 1, 1)
        self.useDefaultLabelCheckbox = QtWidgets.QCheckBox(self.DataViewing)
        self.useDefaultLabelCheckbox.setObjectName("useDefaultLabelCheckbox")
        self.gridLayout_2.addWidget(self.useDefaultLabelCheckbox, 13, 1, 1, 2)
        self.defaultLabelTextLine = QtWidgets.QLineEdit(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultLabelTextLine.sizePolicy().hasHeightForWidth())
        self.defaultLabelTextLine.setSizePolicy(sizePolicy)
        self.defaultLabelTextLine.setObjectName("defaultLabelTextLine")
        self.gridLayout_2.addWidget(self.defaultLabelTextLine, 14, 1, 1, 2)
        self.brectangle = QtWidgets.QRadioButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brectangle.sizePolicy().hasHeightForWidth())
        self.brectangle.setSizePolicy(sizePolicy)
        self.brectangle.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brectangle.setIcon(icon7)
        self.brectangle.setIconSize(QtCore.QSize(35, 35))
        self.brectangle.setObjectName("brectangle")
        self.gridLayout_2.addWidget(self.brectangle, 11, 2, 1, 1)
        self.visionlabel = QtWidgets.QLabel(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visionlabel.sizePolicy().hasHeightForWidth())
        self.visionlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.visionlabel.setFont(font)
        self.visionlabel.setMouseTracking(True)
        self.visionlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.visionlabel.setTextFormat(QtCore.Qt.RichText)
        self.visionlabel.setObjectName("visionlabel")
        self.gridLayout_2.addWidget(self.visionlabel, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.labelLabel = QtWidgets.QLabel(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLabel.sizePolicy().hasHeightForWidth())
        self.labelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLabel.setFont(font)
        self.labelLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout_2.addWidget(self.labelLabel, 9, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.bdswitch = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdswitch.sizePolicy().hasHeightForWidth())
        self.bdswitch.setSizePolicy(sizePolicy)
        self.bdswitch.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdswitch.setIcon(icon8)
        self.bdswitch.setIconSize(QtCore.QSize(35, 35))
        self.bdswitch.setObjectName("bdswitch")
        self.gridLayout_2.addWidget(self.bdswitch, 4, 2, 1, 1)
        self.openlabelButton = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openlabelButton.sizePolicy().hasHeightForWidth())
        self.openlabelButton.setSizePolicy(sizePolicy)
        self.openlabelButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/new list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openlabelButton.setIcon(icon9)
        self.openlabelButton.setIconSize(QtCore.QSize(35, 35))
        self.openlabelButton.setObjectName("openlabelButton")
        self.gridLayout_2.addWidget(self.openlabelButton, 15, 2, 1, 1)
        self.viewallButton = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewallButton.sizePolicy().hasHeightForWidth())
        self.viewallButton.setSizePolicy(sizePolicy)
        self.viewallButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/eye on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewallButton.setIcon(icon10)
        self.viewallButton.setIconSize(QtCore.QSize(35, 35))
        self.viewallButton.setObjectName("viewallButton")
        self.gridLayout_2.addWidget(self.viewallButton, 16, 1, 1, 1)
        self.bellipse = QtWidgets.QRadioButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bellipse.sizePolicy().hasHeightForWidth())
        self.bellipse.setSizePolicy(sizePolicy)
        self.bellipse.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Icons/ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bellipse.setIcon(icon11)
        self.bellipse.setIconSize(QtCore.QSize(35, 35))
        self.bellipse.setObjectName("bellipse")
        self.gridLayout_2.addWidget(self.bellipse, 12, 1, 1, 1)
        self.labelListShow = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelListShow.sizePolicy().hasHeightForWidth())
        self.labelListShow.setSizePolicy(sizePolicy)
        self.labelListShow.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/Icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.labelListShow.setIcon(icon12)
        self.labelListShow.setIconSize(QtCore.QSize(35, 35))
        self.labelListShow.setObjectName("labelListShow")
        self.gridLayout_2.addWidget(self.labelListShow, 16, 2, 1, 1)
        self.gridButton = QtWidgets.QToolButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridButton.sizePolicy().hasHeightForWidth())
        self.gridButton.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/Icons/grids1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gridButton.setIcon(icon13)
        self.gridButton.setIconSize(QtCore.QSize(35, 35))
        self.gridButton.setObjectName("gridButton")
        self.gridLayout_2.addWidget(self.gridButton, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.labellistBox = QtWidgets.QComboBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labellistBox.sizePolicy().hasHeightForWidth())
        self.labellistBox.setSizePolicy(sizePolicy)
        self.labellistBox.setEditable(True)
        self.labellistBox.setObjectName("labellistBox")
        self.gridLayout_2.addWidget(self.labellistBox, 17, 1, 1, 2)
        self.roiButton = QtWidgets.QToolButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roiButton.sizePolicy().hasHeightForWidth())
        self.roiButton.setSizePolicy(sizePolicy)
        self.roiButton.setIconSize(QtCore.QSize(35, 35))
        self.roiButton.setObjectName("roiButton")
        self.gridLayout_2.addWidget(self.roiButton, 6, 1, 1, 1)
        self.openImage = QtWidgets.QComboBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openImage.sizePolicy().hasHeightForWidth())
        self.openImage.setSizePolicy(sizePolicy)
        self.openImage.setAutoFillBackground(True)
        self.openImage.setCurrentText("")
        self.openImage.setIconSize(QtCore.QSize(16, 16))
        self.openImage.setObjectName("openImage")
        self.gridLayout_2.addWidget(self.openImage, 0, 1, 1, 1)
        self.labelButton = QtWidgets.QComboBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelButton.sizePolicy().hasHeightForWidth())
        self.labelButton.setSizePolicy(sizePolicy)
        self.labelButton.setObjectName("labelButton")
        self.gridLayout_2.addWidget(self.labelButton, 7, 2, 1, 1)
        self.openResult = QtWidgets.QComboBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openResult.sizePolicy().hasHeightForWidth())
        self.openResult.setSizePolicy(sizePolicy)
        self.openResult.setAutoFillBackground(True)
        self.openResult.setCurrentText("")
        self.openResult.setIconSize(QtCore.QSize(16, 16))
        self.openResult.setObjectName("openResult")
        self.gridLayout_2.addWidget(self.openResult, 0, 2, 1, 1)
        self.flipButton = QtWidgets.QToolButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipButton.sizePolicy().hasHeightForWidth())
        self.flipButton.setSizePolicy(sizePolicy)
        self.flipButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/Icons/flip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flipButton.setIcon(icon14)
        self.flipButton.setIconSize(QtCore.QSize(35, 35))
        self.flipButton.setObjectName("flipButton")
        self.gridLayout_2.addWidget(self.flipButton, 3, 2, 1, 1)
        self.inspectorButton = QtWidgets.QCheckBox(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inspectorButton.sizePolicy().hasHeightForWidth())
        self.inspectorButton.setSizePolicy(sizePolicy)
        self.inspectorButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/Icons/isymbol_location_position.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inspectorButton.setIcon(icon15)
        self.inspectorButton.setIconSize(QtCore.QSize(35, 35))
        self.inspectorButton.setObjectName("inspectorButton")
        self.gridLayout_2.addWidget(self.inspectorButton, 7, 1, 1, 1)
        self.fitButton = QtWidgets.QPushButton(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitButton.sizePolicy().hasHeightForWidth())
        self.fitButton.setSizePolicy(sizePolicy)
        self.fitButton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/Icons/fitsize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fitButton.setIcon(icon16)
        self.fitButton.setIconSize(QtCore.QSize(35, 35))
        self.fitButton.setObjectName("fitButton")
        self.gridLayout_2.addWidget(self.fitButton, 6, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.DataViewing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea1 = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea1.setMouseTracking(True)
        self.scrollArea1.setAutoFillBackground(True)
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName("scrollArea1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 987, 678))
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea1.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea1)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea2 = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea2.setEnabled(True)
        self.scrollArea2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea2.setMouseTracking(False)
        self.scrollArea2.setAutoFillBackground(True)
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName("scrollArea2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 78, 16))
        self.scrollAreaWidgetContents_2.setAutoFillBackground(True)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.DataViewing, "")
        self.NetworkTraining = QtWidgets.QWidget()
        self.NetworkTraining.setObjectName("NetworkTraining")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.NetworkTraining)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.NetworkTraining)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 831, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RadioButton_MaskLabeling = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.RadioButton_MaskLabeling.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_MaskLabeling.setFont(font)
        self.RadioButton_MaskLabeling.setChecked(True)
        self.RadioButton_MaskLabeling.setObjectName("RadioButton_MaskLabeling")
        self.gridLayout_5.addWidget(self.RadioButton_MaskLabeling, 3, 0, 1, 1)
        self.ComboBox_splittingMode = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.ComboBox_splittingMode.setObjectName("ComboBox_splittingMode")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_splittingMode, 6, 0, 1, 1)
        self.Button_MarkingsPath = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_MarkingsPath.setFont(font)
        self.Button_MarkingsPath.setObjectName("Button_MarkingsPath")
        self.gridLayout_5.addWidget(self.Button_MarkingsPath, 4, 0, 1, 1)
        self.ComboBox_StoreOptions = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.ComboBox_StoreOptions.setObjectName("ComboBox_StoreOptions")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_StoreOptions, 7, 0, 1, 1)
        self.RadioButton_PatchLabeling = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_PatchLabeling.setFont(font)
        self.RadioButton_PatchLabeling.setObjectName("RadioButton_PatchLabeling")
        self.gridLayout_5.addWidget(self.RadioButton_PatchLabeling, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.SpinBox_PatchX = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX.setFont(font)
        self.SpinBox_PatchX.setMaximum(500)
        self.SpinBox_PatchX.setProperty("value", 40)
        self.SpinBox_PatchX.setObjectName("SpinBox_PatchX")
        self.gridLayout_5.addWidget(self.SpinBox_PatchX, 2, 1, 1, 1)
        self.SpinBox_PatchZ = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchZ.setFont(font)
        self.SpinBox_PatchZ.setProperty("value", 5)
        self.SpinBox_PatchZ.setObjectName("SpinBox_PatchZ")
        self.gridLayout_5.addWidget(self.SpinBox_PatchZ, 2, 5, 1, 1)
        self.SpinBox_PatchY = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY.setFont(font)
        self.SpinBox_PatchY.setMaximum(500)
        self.SpinBox_PatchY.setProperty("value", 40)
        self.SpinBox_PatchY.setObjectName("SpinBox_PatchY")
        self.gridLayout_5.addWidget(self.SpinBox_PatchY, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 2, 6, 1, 1)
        self.SpinBox_PatchOverlapp = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp.setFont(font)
        self.SpinBox_PatchOverlapp.setMaximum(1.0)
        self.SpinBox_PatchOverlapp.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp.setObjectName("SpinBox_PatchOverlapp")
        self.gridLayout_5.addWidget(self.SpinBox_PatchOverlapp, 2, 7, 1, 1)
        self.CheckBox_randomShuffle = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.CheckBox_randomShuffle.setObjectName("CheckBox_randomShuffle")
        self.gridLayout_5.addWidget(self.CheckBox_randomShuffle, 7, 3, 1, 1)
        self.Button_DB = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB.setFont(font)
        self.Button_DB.setObjectName("Button_DB")
        self.gridLayout_5.addWidget(self.Button_DB, 0, 0, 1, 1)
        self.Button_OutputPathPatching = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching.setFont(font)
        self.Button_OutputPathPatching.setObjectName("Button_OutputPathPatching")
        self.gridLayout_5.addWidget(self.Button_OutputPathPatching, 4, 3, 1, 1)
        self.Label_OutputPathPatching = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching.setFont(font)
        self.Label_OutputPathPatching.setWordWrap(True)
        self.Label_OutputPathPatching.setObjectName("Label_OutputPathPatching")
        self.gridLayout_5.addWidget(self.Label_OutputPathPatching, 4, 4, 1, 4)
        self.CheckBox_SegmentationMask = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CheckBox_SegmentationMask.setFont(font)
        self.CheckBox_SegmentationMask.setObjectName("CheckBox_SegmentationMask")
        self.gridLayout_5.addWidget(self.CheckBox_SegmentationMask, 7, 1, 1, 1)
        self.Label_SplittingParams = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Label_SplittingParams.setWordWrap(True)
        self.Label_SplittingParams.setObjectName("Label_SplittingParams")
        self.gridLayout_5.addWidget(self.Label_SplittingParams, 6, 3, 1, 1)
        self.TreeWidget_Patients = QtWidgets.QTreeWidget(self.horizontalLayoutWidget_2)
        self.TreeWidget_Patients.setObjectName("TreeWidget_Patients")
        self.TreeWidget_Patients.headerItem().setText(0, "1")
        self.gridLayout_5.addWidget(self.TreeWidget_Patients, 1, 0, 1, 1)
        self.TreeWidget_Datasets = QtWidgets.QTreeWidget(self.horizontalLayoutWidget_2)
        self.TreeWidget_Datasets.setObjectName("TreeWidget_Datasets")
        self.TreeWidget_Datasets.headerItem().setText(0, "1")
        self.gridLayout_5.addWidget(self.TreeWidget_Datasets, 1, 1, 1, 4)
        self.Label_DB = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB.setFont(font)
        self.Label_DB.setObjectName("Label_DB")
        self.gridLayout_5.addWidget(self.Label_DB, 0, 1, 1, 4)
        self.Button_Patching = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Patching.sizePolicy().hasHeightForWidth())
        self.Button_Patching.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching.setFont(font)
        self.Button_Patching.setObjectName("Button_Patching")
        self.gridLayout_5.addWidget(self.Button_Patching, 7, 5, 1, 2)
        self.ComboBox_Patching = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_Patching.sizePolicy().hasHeightForWidth())
        self.ComboBox_Patching.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComboBox_Patching.setFont(font)
        self.ComboBox_Patching.setObjectName("ComboBox_Patching")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.gridLayout_5.addWidget(self.ComboBox_Patching, 3, 3, 1, 1)
        self.Label_MarkingsPath = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Label_MarkingsPath.setWordWrap(True)
        self.Label_MarkingsPath.setObjectName("Label_MarkingsPath")
        self.gridLayout_5.addWidget(self.Label_MarkingsPath, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.NetworkTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Button_useCurrentData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_useCurrentData.setEnabled(False)
        self.Button_useCurrentData.setObjectName("Button_useCurrentData")
        self.verticalLayout_4.addWidget(self.Button_useCurrentData)
        self.Button_selectDataset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_selectDataset.setObjectName("Button_selectDataset")
        self.verticalLayout_4.addWidget(self.Button_selectDataset)
        self.Label_currentDataset = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label_currentDataset.setObjectName("Label_currentDataset")
        self.verticalLayout_4.addWidget(self.Label_currentDataset)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.GroupBox_TrainNN = QtWidgets.QGroupBox(self.NetworkTraining)
        self.GroupBox_TrainNN.setEnabled(False)
        self.GroupBox_TrainNN.setObjectName("GroupBox_TrainNN")
        self.gridLayoutWidget = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 621, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Button_LearningOutputPath = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button_LearningOutputPath.setObjectName("Button_LearningOutputPath")
        self.gridLayout_6.addWidget(self.Button_LearningOutputPath, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 4, 0, 1, 1)
        self.Label_LearningOutputPath = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_LearningOutputPath.setWordWrap(True)
        self.Label_LearningOutputPath.setObjectName("Label_LearningOutputPath")
        self.gridLayout_6.addWidget(self.Label_LearningOutputPath, 0, 2, 1, 1)
        self.ComboBox_DNNs = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_DNNs.setFont(font)
        self.ComboBox_DNNs.setObjectName("ComboBox_DNNs")
        self.gridLayout_6.addWidget(self.ComboBox_DNNs, 0, 0, 1, 1)
        self.DoubleSpinBox_WeightDecay = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_WeightDecay.setFont(font)
        self.DoubleSpinBox_WeightDecay.setDecimals(5)
        self.DoubleSpinBox_WeightDecay.setMaximum(1.0)
        self.DoubleSpinBox_WeightDecay.setSingleStep(0.0001)
        self.DoubleSpinBox_WeightDecay.setProperty("value", 0.0001)
        self.DoubleSpinBox_WeightDecay.setObjectName("DoubleSpinBox_WeightDecay")
        self.gridLayout_6.addWidget(self.DoubleSpinBox_WeightDecay, 4, 1, 1, 1)
        self.DoubleSpinBox_Momentum = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_Momentum.setFont(font)
        self.DoubleSpinBox_Momentum.setMaximum(1.0)
        self.DoubleSpinBox_Momentum.setSingleStep(0.05)
        self.DoubleSpinBox_Momentum.setProperty("value", 0.9)
        self.DoubleSpinBox_Momentum.setObjectName("DoubleSpinBox_Momentum")
        self.gridLayout_6.addWidget(self.DoubleSpinBox_Momentum, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.SpinBox_Epochs = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_Epochs.setFont(font)
        self.SpinBox_Epochs.setMaximum(100000)
        self.SpinBox_Epochs.setProperty("value", 100)
        self.SpinBox_Epochs.setObjectName("SpinBox_Epochs")
        self.gridLayout_6.addWidget(self.SpinBox_Epochs, 3, 3, 1, 1)
        self.LineEdit_LearningRates = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_LearningRates.setFont(font)
        self.LineEdit_LearningRates.setObjectName("LineEdit_LearningRates")
        self.gridLayout_6.addWidget(self.LineEdit_LearningRates, 2, 1, 1, 1)
        self.ComboBox_Optimizers = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_Optimizers.setFont(font)
        self.ComboBox_Optimizers.setObjectName("ComboBox_Optimizers")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.gridLayout_6.addWidget(self.ComboBox_Optimizers, 3, 1, 1, 1)
        self.LineEdit_BatchSizes = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_BatchSizes.setFont(font)
        self.LineEdit_BatchSizes.setObjectName("LineEdit_BatchSizes")
        self.gridLayout_6.addWidget(self.LineEdit_BatchSizes, 2, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 3, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 4, 2, 1, 1, QtCore.Qt.AlignRight)
        self.CheckBox_Nesterov = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Nesterov.setFont(font)
        self.CheckBox_Nesterov.setObjectName("CheckBox_Nesterov")
        self.gridLayout_6.addWidget(self.CheckBox_Nesterov, 5, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 7, 0, 1, 1)
        self.ComboBox_GPU = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.ComboBox_GPU.setObjectName("ComboBox_GPU")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.ComboBox_GPU.addItem("")
        self.gridLayout_6.addWidget(self.ComboBox_GPU, 7, 1, 1, 1)
        self.Button_train = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_train.setFont(font)
        self.Button_train.setObjectName("Button_train")
        self.gridLayout_6.addWidget(self.Button_train, 7, 2, 1, 1)
        self.progressBar_Training = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_Training.setProperty("value", 0)
        self.progressBar_Training.setObjectName("progressBar_Training")
        self.gridLayout_6.addWidget(self.progressBar_Training, 7, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBox_DataAug_horizontalFlip = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_horizontalFlip.setFont(font)
        self.CheckBox_DataAug_horizontalFlip.setObjectName("CheckBox_DataAug_horizontalFlip")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_horizontalFlip)
        self.CheckBox_DataAug_verticalFlip = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_verticalFlip.setFont(font)
        self.CheckBox_DataAug_verticalFlip.setObjectName("CheckBox_DataAug_verticalFlip")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_verticalFlip)
        self.CheckBox_DataAug_Rotation = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_Rotation.setFont(font)
        self.CheckBox_DataAug_Rotation.setObjectName("CheckBox_DataAug_Rotation")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_Rotation)
        self.CheckBox_DataAug_Zoom = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_Zoom.setFont(font)
        self.CheckBox_DataAug_Zoom.setObjectName("CheckBox_DataAug_Zoom")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_Zoom)
        self.CheckBox_DataAug_zcaWeighting = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_zcaWeighting.setFont(font)
        self.CheckBox_DataAug_zcaWeighting.setObjectName("CheckBox_DataAug_zcaWeighting")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_zcaWeighting)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CheckBox_DataAug_HeightShift = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_HeightShift.setFont(font)
        self.CheckBox_DataAug_HeightShift.setObjectName("CheckBox_DataAug_HeightShift")
        self.horizontalLayout_4.addWidget(self.CheckBox_DataAug_HeightShift)
        self.CheckBox_DataAug_WidthShift = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_WidthShift.setFont(font)
        self.CheckBox_DataAug_WidthShift.setObjectName("CheckBox_DataAug_WidthShift")
        self.horizontalLayout_4.addWidget(self.CheckBox_DataAug_WidthShift)
        self.RadioButton_DataAug_contrastStretching = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.RadioButton_DataAug_contrastStretching.setObjectName("RadioButton_DataAug_contrastStretching")
        self.horizontalLayout_4.addWidget(self.RadioButton_DataAug_contrastStretching)
        self.RadioButton_DataAug_histogramEq = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.RadioButton_DataAug_histogramEq.setObjectName("RadioButton_DataAug_histogramEq")
        self.horizontalLayout_4.addWidget(self.RadioButton_DataAug_histogramEq)
        self.RadioButton_DataAug_adaptiveEq = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.RadioButton_DataAug_adaptiveEq.setObjectName("RadioButton_DataAug_adaptiveEq")
        self.horizontalLayout_4.addWidget(self.RadioButton_DataAug_adaptiveEq)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CheckBox_Artifacts = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Artifacts.setFont(font)
        self.CheckBox_Artifacts.setObjectName("CheckBox_Artifacts")
        self.horizontalLayout.addWidget(self.CheckBox_Artifacts)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CheckBox_BodyRegion = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_BodyRegion.setFont(font)
        self.CheckBox_BodyRegion.setObjectName("CheckBox_BodyRegion")
        self.horizontalLayout.addWidget(self.CheckBox_BodyRegion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CheckBox_TWeighting = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_TWeighting.setFont(font)
        self.CheckBox_TWeighting.setObjectName("CheckBox_TWeighting")
        self.horizontalLayout.addWidget(self.CheckBox_TWeighting)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_6.addLayout(self.verticalLayout, 6, 0, 1, 4)
        self.CheckBox_DataAugmentation = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CheckBox_DataAugmentation.setFont(font)
        self.CheckBox_DataAugmentation.setObjectName("CheckBox_DataAugmentation")
        self.gridLayout_6.addWidget(self.CheckBox_DataAugmentation, 5, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.GroupBox_TrainNN)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.NetworkTraining)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 471, 851))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_training_performance = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_training_performance.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_training_performance.setObjectName("verticalLayout_training_performance")
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_8.setStretch(0, 7)
        self.horizontalLayout_8.setStretch(1, 4)
        self.tabWidget.addTab(self.NetworkTraining, "")
        self.NetworkVisualization = QtWidgets.QWidget()
        self.NetworkVisualization.setObjectName("NetworkVisualization")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.NetworkVisualization)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.wyShowArchitecture = QtWidgets.QPushButton(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wyShowArchitecture.sizePolicy().hasHeightForWidth())
        self.wyShowArchitecture.setSizePolicy(sizePolicy)
        self.wyShowArchitecture.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/Icons/biology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wyShowArchitecture.setIcon(icon17)
        self.wyShowArchitecture.setIconSize(QtCore.QSize(30, 30))
        self.wyShowArchitecture.setObjectName("wyShowArchitecture")
        self.gridLayout.addWidget(self.wyShowArchitecture, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.NetworkVisualization)
        self.radioButton_2.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/Icons/layers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_2.setIcon(icon18)
        self.radioButton_2.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.NetworkVisualization)
        self.radioButton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/Icons/funnel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton.setIcon(icon19)
        self.radioButton.setIconSize(QtCore.QSize(30, 30))
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 3, 0, 1, 1)
        self.predictButton = QtWidgets.QPushButton(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictButton.sizePolicy().hasHeightForWidth())
        self.predictButton.setSizePolicy(sizePolicy)
        self.predictButton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/Icons/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predictButton.setIcon(icon20)
        self.predictButton.setIconSize(QtCore.QSize(30, 30))
        self.predictButton.setObjectName("predictButton")
        self.gridLayout.addWidget(self.predictButton, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.wyChooseFile = QtWidgets.QComboBox(self.NetworkVisualization)
        self.wyChooseFile.setObjectName("wyChooseFile")
        self.gridLayout.addWidget(self.wyChooseFile, 1, 0, 1, 1)
        self.wyInputData = QtWidgets.QComboBox(self.NetworkVisualization)
        self.wyInputData.setObjectName("wyInputData")
        self.gridLayout.addWidget(self.wyInputData, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        self.listView = QtWidgets.QListView(self.NetworkVisualization)
        self.listView.setObjectName("listView")
        self.verticalLayout_10.addWidget(self.listView)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_3 = QtWidgets.QRadioButton(self.NetworkVisualization)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/Icons/one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_3.setIcon(icon21)
        self.radioButton_3.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_12.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.NetworkVisualization)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/Icons/two.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_4.setIcon(icon22)
        self.radioButton_4.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_12.addWidget(self.radioButton_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelPatch_2 = QtWidgets.QLabel(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch_2.sizePolicy().hasHeightForWidth())
        self.labelPatch_2.setSizePolicy(sizePolicy)
        self.labelPatch_2.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch_2.setText("")
        self.labelPatch_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch_2.setPixmap(QtGui.QPixmap(":/icons/Icons/alpha.png"))
        self.labelPatch_2.setScaledContents(True)
        self.labelPatch_2.setObjectName("labelPatch_2")
        self.horizontalLayout_12.addWidget(self.labelPatch_2)
        self.lineEdit = QtWidgets.QLineEdit(self.NetworkVisualization)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_12.addWidget(self.lineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelPatch_3 = QtWidgets.QLabel(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch_3.sizePolicy().hasHeightForWidth())
        self.labelPatch_3.setSizePolicy(sizePolicy)
        self.labelPatch_3.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch_3.setText("")
        self.labelPatch_3.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch_3.setPixmap(QtGui.QPixmap(":/icons/Icons/gamma.png"))
        self.labelPatch_3.setScaledContents(True)
        self.labelPatch_3.setObjectName("labelPatch_3")
        self.horizontalLayout_13.addWidget(self.labelPatch_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.NetworkVisualization)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_13.addWidget(self.lineEdit_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.wySubsetSelection = QtWidgets.QPushButton(self.NetworkVisualization)
        self.wySubsetSelection.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/Icons/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wySubsetSelection.setIcon(icon23)
        self.wySubsetSelection.setIconSize(QtCore.QSize(30, 30))
        self.wySubsetSelection.setObjectName("wySubsetSelection")
        self.verticalLayout_12.addWidget(self.wySubsetSelection)
        self.wyPlot = QtWidgets.QComboBox(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wyPlot.sizePolicy().hasHeightForWidth())
        self.wyPlot.setSizePolicy(sizePolicy)
        self.wyPlot.setObjectName("wyPlot")
        self.verticalLayout_12.addWidget(self.wyPlot)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_showing = QtWidgets.QVBoxLayout()
        self.verticalLayout_showing.setObjectName("verticalLayout_showing")
        self.matplotlibwidget_static = MatplotlibWidget(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_static.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_static.setSizePolicy(sizePolicy)
        self.matplotlibwidget_static.setMouseTracking(True)
        self.matplotlibwidget_static.setObjectName("matplotlibwidget_static")
        self.verticalLayout_showing.addWidget(self.matplotlibwidget_static)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelPatch = QtWidgets.QLabel(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch.sizePolicy().hasHeightForWidth())
        self.labelPatch.setSizePolicy(sizePolicy)
        self.labelPatch.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch.setText("")
        self.labelPatch.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch.setPixmap(QtGui.QPixmap(":/icons/Icons/input.png"))
        self.labelPatch.setScaledContents(True)
        self.labelPatch.setObjectName("labelPatch")
        self.horizontalLayout_15.addWidget(self.labelPatch)
        self.horizontalSliderPatch = QtWidgets.QSlider(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSliderPatch.sizePolicy().hasHeightForWidth())
        self.horizontalSliderPatch.setSizePolicy(sizePolicy)
        self.horizontalSliderPatch.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPatch.setObjectName("horizontalSliderPatch")
        self.horizontalLayout_15.addWidget(self.horizontalSliderPatch)
        self.lcdNumberPatch = QtWidgets.QLCDNumber(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberPatch.sizePolicy().hasHeightForWidth())
        self.lcdNumberPatch.setSizePolicy(sizePolicy)
        self.lcdNumberPatch.setObjectName("lcdNumberPatch")
        self.horizontalLayout_15.addWidget(self.lcdNumberPatch)
        self.verticalLayout_showing.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelSlice = QtWidgets.QLabel(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSlice.sizePolicy().hasHeightForWidth())
        self.labelSlice.setSizePolicy(sizePolicy)
        self.labelSlice.setMaximumSize(QtCore.QSize(30, 29))
        self.labelSlice.setText("")
        self.labelSlice.setPixmap(QtGui.QPixmap(":/icons/Icons/research.png"))
        self.labelSlice.setScaledContents(True)
        self.labelSlice.setObjectName("labelSlice")
        self.horizontalLayout_16.addWidget(self.labelSlice)
        self.horizontalSliderSlice = QtWidgets.QSlider(self.NetworkVisualization)
        self.horizontalSliderSlice.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSlice.setObjectName("horizontalSliderSlice")
        self.horizontalLayout_16.addWidget(self.horizontalSliderSlice)
        self.lcdNumberSlice = QtWidgets.QLCDNumber(self.NetworkVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberSlice.sizePolicy().hasHeightForWidth())
        self.lcdNumberSlice.setSizePolicy(sizePolicy)
        self.lcdNumberSlice.setObjectName("lcdNumberSlice")
        self.horizontalLayout_16.addWidget(self.lcdNumberSlice)
        self.verticalLayout_showing.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_6.addLayout(self.verticalLayout_showing)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.NetworkVisualization, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1203, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionColors = QtWidgets.QAction(MainWindow)
        self.actionColors.setObjectName("actionColors")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionLabels = QtWidgets.QAction(MainWindow)
        self.actionLabels.setObjectName("actionLabels")
        self.actionCross = QtWidgets.QAction(MainWindow)
        self.actionCross.setCheckable(True)
        self.actionCross.setObjectName("actionCross")
        self.actionCross_Off = QtWidgets.QAction(MainWindow)
        self.actionCross_Off.setObjectName("actionCross_Off")
        self.actionProcess_Observer = QtWidgets.QAction(MainWindow)
        self.actionProcess_Observer.setObjectName("actionProcess_Observer")
        self.actionLabeling = QtWidgets.QAction(MainWindow)
        self.actionLabeling.setObjectName("actionLabeling")
        self.actionNetworks = QtWidgets.QAction(MainWindow)
        self.actionNetworks.setObjectName("actionNetworks")
        self.actionData_Viewing = QtWidgets.QAction(MainWindow)
        self.actionData_Viewing.setCheckable(True)
        self.actionData_Viewing.setChecked(True)
        self.actionData_Viewing.setObjectName("actionData_Viewing")
        self.actionNetwork_Training = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Training.setCheckable(True)
        self.actionNetwork_Training.setChecked(True)
        self.actionNetwork_Training.setObjectName("actionNetwork_Training")
        self.actionNetwork_Visualization = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Visualization.setCheckable(True)
        self.actionNetwork_Visualization.setChecked(True)
        self.actionNetwork_Visualization.setObjectName("actionNetwork_Visualization")
        self.actionNetwork_Interface = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Interface.setCheckable(False)
        self.actionNetwork_Interface.setObjectName("actionNetwork_Interface")
        self.actionlabeling = QtWidgets.QAction(MainWindow)
        self.actionlabeling.setObjectName("actionlabeling")
        self.actionNetwork_Training_2 = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Training_2.setObjectName("actionNetwork_Training_2")
        self.actionNetwork_Visulization_2 = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Visulization_2.setObjectName("actionNetwork_Visulization_2")
        self.actionNetwork_Testing = QtWidgets.QAction(MainWindow)
        self.actionNetwork_Testing.setObjectName("actionNetwork_Testing")
        self.actionAbout_Network_Training = QtWidgets.QAction(MainWindow)
        self.actionAbout_Network_Training.setObjectName("actionAbout_Network_Training")
        self.actionAbout_Network_Visualization = QtWidgets.QAction(MainWindow)
        self.actionAbout_Network_Visualization.setObjectName("actionAbout_Network_Visualization")
        self.actionImage_and_Result_Showing = QtWidgets.QAction(MainWindow)
        self.actionImage_and_Result_Showing.setObjectName("actionImage_and_Result_Showing")
        self.actionAbout_Labeling = QtWidgets.QAction(MainWindow)
        self.actionAbout_Labeling.setObjectName("actionAbout_Labeling")
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuSetting.addAction(self.actionColors)
        self.menuSetting.addAction(self.actionLabels)
        self.menuSetting.addAction(self.actionNetworks)
        self.menuHelp.addAction(self.actionImage_and_Result_Showing)
        self.menuHelp.addAction(self.actionAbout_Labeling)
        self.menuHelp.addAction(self.actionAbout_Network_Training)
        self.menuHelp.addAction(self.actionNetwork_Testing)
        self.menuHelp.addAction(self.actionAbout_Network_Visualization)
        self.menuView.addAction(self.actionData_Viewing)
        self.menuView.addAction(self.actionNetwork_Training)
        self.menuView.addAction(self.actionNetwork_Visualization)
        self.menuView.addAction(self.actionNetwork_Interface)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deep Learning for Medical Image"))
        self.labelResult.setText(_translate("MainWindow", "Viewing"))
        self.bnoselect.setToolTip(_translate("MainWindow", "No selection\n"
"left mouse move image\n"
"right mouse zoom image\n"
"after rotate view_image\n"
"please click_event this button\n"
"wheel change slice"))
        self.bselectoron.setToolTip(_translate("MainWindow", "Label On/Off"))
        self.blasso.setToolTip(_translate("MainWindow", "Lasso"))
        self.deleteButton.setToolTip(_translate("MainWindow", "Delete the selected label"))
        self.infoButton.setToolTip(_translate("MainWindow", "Load variables from workspace"))
        self.cursorCross.setToolTip(_translate("MainWindow", "Set cross hair for labeling"))
        self.useDefaultLabelCheckbox.setToolTip(_translate("MainWindow", "Use Default Class Label"))
        self.useDefaultLabelCheckbox.setText(_translate("MainWindow", "Default Label"))
        self.defaultLabelTextLine.setToolTip(_translate("MainWindow", "Write the  Label Name"))
        self.brectangle.setToolTip(_translate("MainWindow", "Rectangular"))
        self.visionlabel.setText(_translate("MainWindow", "2D"))
        self.labelLabel.setText(_translate("MainWindow", "Labeling"))
        self.bdswitch.setToolTip(_translate("MainWindow", "2D/3D Switch\n"
"after change of dimension\n"
"switch on Overlay"))
        self.openlabelButton.setToolTip(_translate("MainWindow", "Choose File to Open another\n"
"Label List"))
        self.viewallButton.setToolTip(_translate("MainWindow", "View On/Off all labels "))
        self.bellipse.setToolTip(_translate("MainWindow", "Ellipse"))
        self.labelListShow.setToolTip(_translate("MainWindow", "<html><head/><body><p>show label list</p><p>update labe llist</p></body></html>"))
        self.gridButton.setToolTip(_translate("MainWindow", "Select grids"))
        self.gridButton.setText(_translate("MainWindow", "..."))
        self.labellistBox.setCurrentText(_translate("MainWindow", "Label List"))
        self.roiButton.setToolTip(_translate("MainWindow", "Show Image Intensity\n"
"in the Region of Interest"))
        self.roiButton.setText(_translate("MainWindow", "ROI"))
        self.openImage.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open Image</p></body></html>"))
        self.labelButton.setToolTip(_translate("MainWindow", "show class name"))
        self.openResult.setToolTip(_translate("MainWindow", "Open Result File"))
        self.flipButton.setToolTip(_translate("MainWindow", "Flip Image"))
        self.inspectorButton.setToolTip(_translate("MainWindow", "cursor inspector"))
        self.fitButton.setToolTip(_translate("MainWindow", "Fit imgae view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataViewing), _translate("MainWindow", "Data Viewing"))
        self.groupBox.setTitle(_translate("MainWindow", "Database and Patching"))
        self.RadioButton_MaskLabeling.setText(_translate("MainWindow", "Mask Labeling"))
        self.ComboBox_splittingMode.setItemText(0, _translate("MainWindow", "Select Data Spliting ..."))
        self.ComboBox_splittingMode.setItemText(1, _translate("MainWindow", "Simple Random Samples"))
        self.ComboBox_splittingMode.setItemText(2, _translate("MainWindow", "Crossvalidation"))
        self.ComboBox_splittingMode.setItemText(3, _translate("MainWindow", "Patient Crossvalidation"))
        self.Button_MarkingsPath.setText(_translate("MainWindow", "Markings Path"))
        self.ComboBox_StoreOptions.setItemText(0, _translate("MainWindow", "Do not store on HD"))
        self.ComboBox_StoreOptions.setItemText(1, _translate("MainWindow", "H5PY"))
        self.ComboBox_StoreOptions.setItemText(2, _translate("MainWindow", "Patch based"))
        self.RadioButton_PatchLabeling.setText(_translate("MainWindow", "Patch Labeling"))
        self.label_8.setText(_translate("MainWindow", "x"))
        self.label_7.setText(_translate("MainWindow", "Patch Size:"))
        self.label_14.setText(_translate("MainWindow", "x"))
        self.label_15.setText(_translate("MainWindow", "Overlap:"))
        self.CheckBox_randomShuffle.setText(_translate("MainWindow", "Random Shuffle"))
        self.Button_DB.setText(_translate("MainWindow", "Select Database"))
        self.Button_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.Label_OutputPathPatching.setText(_translate("MainWindow", "Output Path"))
        self.CheckBox_SegmentationMask.setText(_translate("MainWindow", "Using Segmentation Masks"))
        self.Label_SplittingParams.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#3465a4;\">Splitting Params</span></p></body></html>"))
        self.Label_DB.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#3465a4;\">No Database selected</span></p></body></html>"))
        self.Button_Patching.setText(_translate("MainWindow", "Perform Patching"))
        self.ComboBox_Patching.setItemText(0, _translate("MainWindow", "Select Patching Mode ..."))
        self.ComboBox_Patching.setItemText(1, _translate("MainWindow", "2D"))
        self.ComboBox_Patching.setItemText(2, _translate("MainWindow", "3D"))
        self.Label_MarkingsPath.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#3465a4;\">Markings Path</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dataset for Deep Learning"))
        self.Button_useCurrentData.setText(_translate("MainWindow", "Use current data"))
        self.Button_selectDataset.setText(_translate("MainWindow", "Select Dataset"))
        self.Label_currentDataset.setText(_translate("MainWindow", "No Dataset is selected!"))
        self.GroupBox_TrainNN.setTitle(_translate("MainWindow", "Train Deep Neural Network"))
        self.Button_LearningOutputPath.setText(_translate("MainWindow", "Learning Output Path"))
        self.label_19.setText(_translate("MainWindow", "Optimizer:"))
        self.label_3.setText(_translate("MainWindow", "Learning Rate/s:"))
        self.label_20.setText(_translate("MainWindow", "Weight Decay:"))
        self.Label_LearningOutputPath.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#3465a4;\">Select Network Output Path!</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Batch Size/s:"))
        self.LineEdit_LearningRates.setText(_translate("MainWindow", "0.01"))
        self.ComboBox_Optimizers.setItemText(0, _translate("MainWindow", "SGD"))
        self.ComboBox_Optimizers.setItemText(1, _translate("MainWindow", "RMSprop"))
        self.ComboBox_Optimizers.setItemText(2, _translate("MainWindow", "Adagrad"))
        self.ComboBox_Optimizers.setItemText(3, _translate("MainWindow", "Adadelta"))
        self.ComboBox_Optimizers.setItemText(4, _translate("MainWindow", "Adam"))
        self.LineEdit_BatchSizes.setText(_translate("MainWindow", "128"))
        self.label_21.setText(_translate("MainWindow", "Epochs:"))
        self.label_22.setText(_translate("MainWindow", "Momentum:"))
        self.CheckBox_Nesterov.setText(_translate("MainWindow", "Nesterov"))
        self.label_23.setText(_translate("MainWindow", "GPU:"))
        self.ComboBox_GPU.setItemText(0, _translate("MainWindow", "0"))
        self.ComboBox_GPU.setItemText(1, _translate("MainWindow", "1"))
        self.ComboBox_GPU.setItemText(2, _translate("MainWindow", "2"))
        self.ComboBox_GPU.setItemText(3, _translate("MainWindow", "3"))
        self.ComboBox_GPU.setItemText(4, _translate("MainWindow", "4"))
        self.Button_train.setText(_translate("MainWindow", "Perform Training"))
        self.CheckBox_DataAug_horizontalFlip.setText(_translate("MainWindow", "Horizontal Flip"))
        self.CheckBox_DataAug_verticalFlip.setText(_translate("MainWindow", "Vertical Flip"))
        self.CheckBox_DataAug_Rotation.setText(_translate("MainWindow", "Rotation"))
        self.CheckBox_DataAug_Zoom.setText(_translate("MainWindow", "Zoom"))
        self.CheckBox_DataAug_zcaWeighting.setText(_translate("MainWindow", "ZCA Whitening"))
        self.CheckBox_DataAug_HeightShift.setText(_translate("MainWindow", "Height Shift"))
        self.CheckBox_DataAug_WidthShift.setText(_translate("MainWindow", "Width Shift"))
        self.RadioButton_DataAug_contrastStretching.setText(_translate("MainWindow", "Contrast Stretching"))
        self.RadioButton_DataAug_histogramEq.setText(_translate("MainWindow", "Histogram Eq"))
        self.RadioButton_DataAug_adaptiveEq.setText(_translate("MainWindow", "Adaptive E&q"))
        self.label.setText(_translate("MainWindow", "Select Multiclasses:"))
        self.CheckBox_Artifacts.setText(_translate("MainWindow", "Artifacts"))
        self.CheckBox_BodyRegion.setText(_translate("MainWindow", "Body Region"))
        self.CheckBox_TWeighting.setText(_translate("MainWindow", "T Weighting"))
        self.CheckBox_DataAugmentation.setText(_translate("MainWindow", "Data Augmentation"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Training Performance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NetworkTraining), _translate("MainWindow", "Network Training"))
        self.wyShowArchitecture.setToolTip(_translate("MainWindow", "Show network architechture"))
        self.radioButton_2.setToolTip(_translate("MainWindow", "Feature Maps"))
        self.radioButton.setToolTip(_translate("MainWindow", "Weights of Filters"))
        self.predictButton.setStatusTip(_translate("MainWindow", "perform prediction"))
        self.wyChooseFile.setToolTip(_translate("MainWindow", "Choose model"))
        self.wyInputData.setToolTip(_translate("MainWindow", "Choose test data"))
        self.radioButton_3.setText(_translate("MainWindow", "Plot &1. Input"))
        self.radioButton_4.setText(_translate("MainWindow", "Plot &2. Input"))
        self.labelPatch_2.setToolTip(_translate("MainWindow", "Feasible Result to Obtain"))
        self.lineEdit.setText(_translate("MainWindow", "0.0000001"))
        self.labelPatch_3.setToolTip(_translate("MainWindow", "Step Size"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.19"))
        self.wySubsetSelection.setToolTip(_translate("MainWindow", "Created Input Patches With Subset Selection"))
        self.labelPatch.setToolTip(_translate("MainWindow", "Number of Input Patch"))
        self.labelSlice.setToolTip(_translate("MainWindow", "Number of Feature Maps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NetworkVisualization), _translate("MainWindow", "Network Visualization"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setti&ng"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_file.setText(_translate("MainWindow", "&Open file"))
        self.actionSave.setText(_translate("MainWindow", "&Save current"))
        self.actionColors.setText(_translate("MainWindow", "&Colors"))
        self.actionLoad.setText(_translate("MainWindow", "&Load previous"))
        self.actionLabels.setText(_translate("MainWindow", "&Labels"))
        self.actionCross.setText(_translate("MainWindow", "Cross "))
        self.actionCross_Off.setText(_translate("MainWindow", "Cross Off"))
        self.actionProcess_Observer.setText(_translate("MainWindow", "Process Observer"))
        self.actionLabeling.setText(_translate("MainWindow", "Image and result showing"))
        self.actionNetworks.setText(_translate("MainWindow", "&Networks"))
        self.actionData_Viewing.setText(_translate("MainWindow", "&Data Viewing"))
        self.actionNetwork_Training.setText(_translate("MainWindow", "&Network Training"))
        self.actionNetwork_Visualization.setText(_translate("MainWindow", "Network &Visualization"))
        self.actionNetwork_Interface.setText(_translate("MainWindow", "Network &Interface"))
        self.actionlabeling.setText(_translate("MainWindow", "About Labeling"))
        self.actionNetwork_Training_2.setText(_translate("MainWindow", "About Network Training"))
        self.actionNetwork_Visulization_2.setText(_translate("MainWindow", "About Network Visulization"))
        self.actionNetwork_Testing.setText(_translate("MainWindow", "A&bout Network Testing"))
        self.actionAbout_Network_Training.setText(_translate("MainWindow", "About &Network Training"))
        self.actionAbout_Network_Visualization.setText(_translate("MainWindow", "About Network &Visualization"))
        self.actionImage_and_Result_Showing.setText(_translate("MainWindow", "&Image and Result Showing"))
        self.actionAbout_Labeling.setText(_translate("MainWindow", "&About Labeling"))

from configGUI.matplotlibwidget import MatplotlibWidget
import configGUI.resrc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

