# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yannick\Google Drive\Masterarbeit\30_Content\CNNArt\DeepLearningArt\DLArt_GUI\dlart_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DLArt_GUI(object):
    def setupUi(self, DLArt_GUI):
        DLArt_GUI.setObjectName("DLArt_GUI")
        DLArt_GUI.resize(1384, 935)
        self.centralWidget = QtWidgets.QWidget(DLArt_GUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1361, 851))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Multiclass = QtWidgets.QWidget()
        self.Tab_Multiclass.setObjectName("Tab_Multiclass")
        self.groupBox = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 511, 501))
        self.groupBox.setObjectName("groupBox")
        self.SpinBox_PatchX = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchX.setGeometry(QtCore.QRect(90, 241, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX.setFont(font)
        self.SpinBox_PatchX.setMaximum(500)
        self.SpinBox_PatchX.setProperty("value", 40)
        self.SpinBox_PatchX.setObjectName("SpinBox_PatchX")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.SpinBox_PatchY = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchY.setGeometry(QtCore.QRect(180, 240, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY.setFont(font)
        self.SpinBox_PatchY.setMaximum(500)
        self.SpinBox_PatchY.setProperty("value", 40)
        self.SpinBox_PatchY.setObjectName("SpinBox_PatchY")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(340, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.SpinBox_PatchOverlapp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.SpinBox_PatchOverlapp.setGeometry(QtCore.QRect(400, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp.setFont(font)
        self.SpinBox_PatchOverlapp.setMaximum(1.0)
        self.SpinBox_PatchOverlapp.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp.setObjectName("SpinBox_PatchOverlapp")
        self.Button_Patching = QtWidgets.QPushButton(self.groupBox)
        self.Button_Patching.setGeometry(QtCore.QRect(370, 450, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching.setFont(font)
        self.Button_Patching.setObjectName("Button_Patching")
        self.TreeWidget_Patients = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Patients.setGeometry(QtCore.QRect(10, 78, 151, 151))
        self.TreeWidget_Patients.setObjectName("TreeWidget_Patients")
        self.TreeWidget_Patients.headerItem().setText(0, "1")
        self.TreeWidget_Datasets = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Datasets.setGeometry(QtCore.QRect(180, 78, 321, 151))
        self.TreeWidget_Datasets.setObjectName("TreeWidget_Datasets")
        self.TreeWidget_Datasets.headerItem().setText(0, "1")
        self.Button_DB = QtWidgets.QPushButton(self.groupBox)
        self.Button_DB.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB.setFont(font)
        self.Button_DB.setObjectName("Button_DB")
        self.Label_DB = QtWidgets.QLabel(self.groupBox)
        self.Label_DB.setGeometry(QtCore.QRect(130, 35, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB.setFont(font)
        self.Label_DB.setObjectName("Label_DB")
        self.Button_OutputPathPatching = QtWidgets.QPushButton(self.groupBox)
        self.Button_OutputPathPatching.setGeometry(QtCore.QRect(20, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching.setFont(font)
        self.Button_OutputPathPatching.setObjectName("Button_OutputPathPatching")
        self.Label_OutputPathPatching = QtWidgets.QLabel(self.groupBox)
        self.Label_OutputPathPatching.setGeometry(QtCore.QRect(130, 360, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching.setFont(font)
        self.Label_OutputPathPatching.setObjectName("Label_OutputPathPatching")
        self.Button_MarkingsPath = QtWidgets.QPushButton(self.groupBox)
        self.Button_MarkingsPath.setGeometry(QtCore.QRect(20, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_MarkingsPath.setFont(font)
        self.Button_MarkingsPath.setObjectName("Button_MarkingsPath")
        self.Label_MarkingsPath = QtWidgets.QLabel(self.groupBox)
        self.Label_MarkingsPath.setGeometry(QtCore.QRect(130, 320, 361, 31))
        self.Label_MarkingsPath.setObjectName("Label_MarkingsPath")
        self.RadioButton_MaskLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_MaskLabeling.setEnabled(True)
        self.RadioButton_MaskLabeling.setGeometry(QtCore.QRect(20, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_MaskLabeling.setFont(font)
        self.RadioButton_MaskLabeling.setChecked(True)
        self.RadioButton_MaskLabeling.setObjectName("RadioButton_MaskLabeling")
        self.RadioButton_PatchLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_PatchLabeling.setGeometry(QtCore.QRect(160, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_PatchLabeling.setFont(font)
        self.RadioButton_PatchLabeling.setObjectName("RadioButton_PatchLabeling")
        self.ComboBox_Patching = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_Patching.setGeometry(QtCore.QRect(330, 282, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComboBox_Patching.setFont(font)
        self.ComboBox_Patching.setObjectName("ComboBox_Patching")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.SpinBox_PatchZ = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchZ.setGeometry(QtCore.QRect(270, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchZ.setFont(font)
        self.SpinBox_PatchZ.setProperty("value", 5)
        self.SpinBox_PatchZ.setObjectName("SpinBox_PatchZ")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(250, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ComboBox_StoreOptions = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_StoreOptions.setGeometry(QtCore.QRect(20, 450, 151, 31))
        self.ComboBox_StoreOptions.setObjectName("ComboBox_StoreOptions")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_splittingMode = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_splittingMode.setGeometry(QtCore.QRect(20, 400, 171, 31))
        self.ComboBox_splittingMode.setObjectName("ComboBox_splittingMode")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.Label_SplittingParams = QtWidgets.QLabel(self.groupBox)
        self.Label_SplittingParams.setGeometry(QtCore.QRect(210, 405, 271, 21))
        self.Label_SplittingParams.setObjectName("Label_SplittingParams")
        self.GroupBox_TrainNN = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.GroupBox_TrainNN.setEnabled(False)
        self.GroupBox_TrainNN.setGeometry(QtCore.QRect(530, 10, 571, 601))
        self.GroupBox_TrainNN.setObjectName("GroupBox_TrainNN")
        self.Button_LearningOutputPath = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_LearningOutputPath.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.Button_LearningOutputPath.setObjectName("Button_LearningOutputPath")
        self.Label_LearningOutputPath = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.Label_LearningOutputPath.setGeometry(QtCore.QRect(150, 75, 311, 21))
        self.Label_LearningOutputPath.setObjectName("Label_LearningOutputPath")
        self.Button_train = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_train.setGeometry(QtCore.QRect(220, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_train.setFont(font)
        self.Button_train.setObjectName("Button_train")
        self.ProgressBar_training = QtWidgets.QProgressBar(self.GroupBox_TrainNN)
        self.ProgressBar_training.setGeometry(QtCore.QRect(330, 540, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProgressBar_training.setFont(font)
        self.ProgressBar_training.setProperty("value", 100)
        self.ProgressBar_training.setObjectName("ProgressBar_training")
        self.ComboBox_DNNs = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_DNNs.setGeometry(QtCore.QRect(10, 20, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_DNNs.setFont(font)
        self.ComboBox_DNNs.setObjectName("ComboBox_DNNs")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 200, 281, 106))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(11, 11, 11, 11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.DoubleSpinBox_WeightDecay = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_WeightDecay.setFont(font)
        self.DoubleSpinBox_WeightDecay.setDecimals(5)
        self.DoubleSpinBox_WeightDecay.setMaximum(1.0)
        self.DoubleSpinBox_WeightDecay.setSingleStep(0.0001)
        self.DoubleSpinBox_WeightDecay.setProperty("value", 0.0001)
        self.DoubleSpinBox_WeightDecay.setObjectName("DoubleSpinBox_WeightDecay")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DoubleSpinBox_WeightDecay)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.DoubleSpinBox_Momentum = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DoubleSpinBox_Momentum.setFont(font)
        self.DoubleSpinBox_Momentum.setMaximum(1.0)
        self.DoubleSpinBox_Momentum.setSingleStep(0.05)
        self.DoubleSpinBox_Momentum.setProperty("value", 0.9)
        self.DoubleSpinBox_Momentum.setObjectName("DoubleSpinBox_Momentum")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DoubleSpinBox_Momentum)
        self.CheckBox_Nesterov = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Nesterov.setFont(font)
        self.CheckBox_Nesterov.setObjectName("CheckBox_Nesterov")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CheckBox_Nesterov)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 501, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CheckBox_Artifacts = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_Artifacts.setFont(font)
        self.CheckBox_Artifacts.setObjectName("CheckBox_Artifacts")
        self.horizontalLayout.addWidget(self.CheckBox_Artifacts)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CheckBox_BodyRegion = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_BodyRegion.setFont(font)
        self.CheckBox_BodyRegion.setObjectName("CheckBox_BodyRegion")
        self.horizontalLayout.addWidget(self.CheckBox_BodyRegion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CheckBox_TWeighting = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_TWeighting.setFont(font)
        self.CheckBox_TWeighting.setObjectName("CheckBox_TWeighting")
        self.horizontalLayout.addWidget(self.CheckBox_TWeighting)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.GroupBox_TrainNN)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 551, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CheckBox_DataAugmentation = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CheckBox_DataAugmentation.setFont(font)
        self.CheckBox_DataAugmentation.setObjectName("CheckBox_DataAugmentation")
        self.verticalLayout.addWidget(self.CheckBox_DataAugmentation)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBox_DataAug_horizontalFlip = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_horizontalFlip.setFont(font)
        self.CheckBox_DataAug_horizontalFlip.setObjectName("CheckBox_DataAug_horizontalFlip")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_horizontalFlip)
        self.CheckBox_DataAug_verticalFlip = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_verticalFlip.setFont(font)
        self.CheckBox_DataAug_verticalFlip.setObjectName("CheckBox_DataAug_verticalFlip")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_verticalFlip)
        self.CheckBox_DataAug_Rotation = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_Rotation.setFont(font)
        self.CheckBox_DataAug_Rotation.setObjectName("CheckBox_DataAug_Rotation")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_Rotation)
        self.CheckBox_DataAug_Zoom = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.CheckBox_DataAug_Zoom.setObjectName("CheckBox_DataAug_Zoom")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_Zoom)
        self.CheckBox_DataAug_zcaWeighting = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_zcaWeighting.setFont(font)
        self.CheckBox_DataAug_zcaWeighting.setObjectName("CheckBox_DataAug_zcaWeighting")
        self.horizontalLayout_2.addWidget(self.CheckBox_DataAug_zcaWeighting)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBox_DataAug_HeightShift = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_HeightShift.setFont(font)
        self.CheckBox_DataAug_HeightShift.setObjectName("CheckBox_DataAug_HeightShift")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_HeightShift)
        self.CheckBox_DataAug_WidthShift = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CheckBox_DataAug_WidthShift.setFont(font)
        self.CheckBox_DataAug_WidthShift.setObjectName("CheckBox_DataAug_WidthShift")
        self.horizontalLayout_3.addWidget(self.CheckBox_DataAug_WidthShift)
        self.RadioButton_DataAug_contrastStretching = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_contrastStretching.setObjectName("RadioButton_DataAug_contrastStretching")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_contrastStretching)
        self.RadioButton_DataAug_histogramEq = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_histogramEq.setObjectName("RadioButton_DataAug_histogramEq")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_histogramEq)
        self.RadioButton_DataAug_adaptiveEq = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RadioButton_DataAug_adaptiveEq.setObjectName("RadioButton_DataAug_adaptiveEq")
        self.horizontalLayout_3.addWidget(self.RadioButton_DataAug_adaptiveEq)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.LineEdit_LearningRates = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_LearningRates.setGeometry(QtCore.QRect(250, 121, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_LearningRates.setFont(font)
        self.LineEdit_LearningRates.setObjectName("LineEdit_LearningRates")
        self.label_3 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ComboBox_Optimizers = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_Optimizers.setGeometry(QtCore.QRect(150, 150, 221, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_Optimizers.setFont(font)
        self.ComboBox_Optimizers.setObjectName("ComboBox_Optimizers")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.ComboBox_Optimizers.addItem("")
        self.LineEdit_BatchSizes = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_BatchSizes.setGeometry(QtCore.QRect(500, 120, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_BatchSizes.setFont(font)
        self.LineEdit_BatchSizes.setObjectName("LineEdit_BatchSizes")
        self.label_2 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_2.setGeometry(QtCore.QRect(400, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_8.setGeometry(QtCore.QRect(400, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.SpinBox_Epochs = QtWidgets.QSpinBox(self.GroupBox_TrainNN)
        self.SpinBox_Epochs.setGeometry(QtCore.QRect(500, 150, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_Epochs.setFont(font)
        self.SpinBox_Epochs.setMaximum(100000)
        self.SpinBox_Epochs.setProperty("value", 100)
        self.SpinBox_Epochs.setObjectName("SpinBox_Epochs")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 519, 511, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.Button_useCurrentData = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_useCurrentData.setEnabled(False)
        self.Button_useCurrentData.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.Button_useCurrentData.setObjectName("Button_useCurrentData")
        self.Button_selectDataset = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_selectDataset.setGeometry(QtCore.QRect(140, 30, 361, 31))
        self.Button_selectDataset.setObjectName("Button_selectDataset")
        self.Label_currentDataset = QtWidgets.QLabel(self.groupBox_4)
        self.Label_currentDataset.setGeometry(QtCore.QRect(10, 70, 491, 20))
        self.Label_currentDataset.setObjectName("Label_currentDataset")
        self.tabWidget.addTab(self.Tab_Multiclass, "")
        self.Tab_GAN = QtWidgets.QWidget()
        self.Tab_GAN.setObjectName("Tab_GAN")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Tab_GAN)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 521, 401))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Button_DB_ArtGAN = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_DB_ArtGAN.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB_ArtGAN.setFont(font)
        self.Button_DB_ArtGAN.setObjectName("Button_DB_ArtGAN")
        self.Label_DB_ArtGAN = QtWidgets.QLabel(self.groupBox_2)
        self.Label_DB_ArtGAN.setGeometry(QtCore.QRect(130, 30, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB_ArtGAN.setFont(font)
        self.Label_DB_ArtGAN.setObjectName("Label_DB_ArtGAN")
        self.TreeWidget_Patients_ArtGAN = QtWidgets.QTreeWidget(self.groupBox_2)
        self.TreeWidget_Patients_ArtGAN.setGeometry(QtCore.QRect(10, 70, 151, 151))
        self.TreeWidget_Patients_ArtGAN.setObjectName("TreeWidget_Patients_ArtGAN")
        self.TreeWidget_Patients_ArtGAN.headerItem().setText(0, "1")
        self.TreeWidget_Datasets_ArtGAN = QtWidgets.QTreeWidget(self.groupBox_2)
        self.TreeWidget_Datasets_ArtGAN.setGeometry(QtCore.QRect(180, 70, 321, 151))
        self.TreeWidget_Datasets_ArtGAN.setObjectName("TreeWidget_Datasets_ArtGAN")
        self.TreeWidget_Datasets_ArtGAN.headerItem().setText(0, "1")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.SpinBox_PatchY_ArtGAN = QtWidgets.QSpinBox(self.groupBox_2)
        self.SpinBox_PatchY_ArtGAN.setGeometry(QtCore.QRect(180, 230, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY_ArtGAN.setFont(font)
        self.SpinBox_PatchY_ArtGAN.setMaximum(500)
        self.SpinBox_PatchY_ArtGAN.setProperty("value", 40)
        self.SpinBox_PatchY_ArtGAN.setObjectName("SpinBox_PatchY_ArtGAN")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(160, 230, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.SpinBox_PatchX_ArtGAN = QtWidgets.QSpinBox(self.groupBox_2)
        self.SpinBox_PatchX_ArtGAN.setGeometry(QtCore.QRect(90, 231, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX_ArtGAN.setFont(font)
        self.SpinBox_PatchX_ArtGAN.setMaximum(500)
        self.SpinBox_PatchX_ArtGAN.setProperty("value", 40)
        self.SpinBox_PatchX_ArtGAN.setObjectName("SpinBox_PatchX_ArtGAN")
        self.SpinBox_PatchOverlapp_ArtGAN = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.SpinBox_PatchOverlapp_ArtGAN.setGeometry(QtCore.QRect(400, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp_ArtGAN.setFont(font)
        self.SpinBox_PatchOverlapp_ArtGAN.setMaximum(1.0)
        self.SpinBox_PatchOverlapp_ArtGAN.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp_ArtGAN.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp_ArtGAN.setObjectName("SpinBox_PatchOverlapp_ArtGAN")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(340, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ComboBox_StoreOptions_ArtGAN = QtWidgets.QComboBox(self.groupBox_2)
        self.ComboBox_StoreOptions_ArtGAN.setGeometry(QtCore.QRect(10, 330, 151, 31))
        self.ComboBox_StoreOptions_ArtGAN.setObjectName("ComboBox_StoreOptions_ArtGAN")
        self.ComboBox_StoreOptions_ArtGAN.addItem("")
        self.ComboBox_StoreOptions_ArtGAN.addItem("")
        self.ComboBox_StoreOptions_ArtGAN.addItem("")
        self.Button_OutputPathPatching_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_OutputPathPatching_2.setGeometry(QtCore.QRect(10, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching_2.setFont(font)
        self.Button_OutputPathPatching_2.setObjectName("Button_OutputPathPatching_2")
        self.Button_Patching_ArtGAN = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_Patching_ArtGAN.setGeometry(QtCore.QRect(370, 330, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching_ArtGAN.setFont(font)
        self.Button_Patching_ArtGAN.setObjectName("Button_Patching_ArtGAN")
        self.Label_OutputPathPatching_ArtGAN = QtWidgets.QLabel(self.groupBox_2)
        self.Label_OutputPathPatching_ArtGAN.setGeometry(QtCore.QRect(120, 280, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching_ArtGAN.setFont(font)
        self.Label_OutputPathPatching_ArtGAN.setObjectName("Label_OutputPathPatching_ArtGAN")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Tab_GAN)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 460, 511, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.Button_useCurrentData_ArtGAN = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_useCurrentData_ArtGAN.setEnabled(False)
        self.Button_useCurrentData_ArtGAN.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.Button_useCurrentData_ArtGAN.setObjectName("Button_useCurrentData_ArtGAN")
        self.Button_selectDataset_ArtGAN = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_selectDataset_ArtGAN.setGeometry(QtCore.QRect(140, 30, 361, 31))
        self.Button_selectDataset_ArtGAN.setObjectName("Button_selectDataset_ArtGAN")
        self.Label_currentDataset_ArtGAN = QtWidgets.QLabel(self.groupBox_5)
        self.Label_currentDataset_ArtGAN.setGeometry(QtCore.QRect(10, 70, 491, 20))
        self.Label_currentDataset_ArtGAN.setObjectName("Label_currentDataset_ArtGAN")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Tab_GAN)
        self.groupBox_6.setGeometry(QtCore.QRect(580, 10, 791, 681))
        self.groupBox_6.setObjectName("groupBox_6")
        self.Button_ShowDataset = QtWidgets.QPushButton(self.groupBox_6)
        self.Button_ShowDataset.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.Button_ShowDataset.setObjectName("Button_ShowDataset")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 771, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_ArtGAN = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_ArtGAN.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_ArtGAN.setSpacing(6)
        self.verticalLayout_ArtGAN.setObjectName("verticalLayout_ArtGAN")
        self.HorizontalSlider_ArtGAN = QtWidgets.QSlider(self.groupBox_6)
        self.HorizontalSlider_ArtGAN.setGeometry(QtCore.QRect(20, 580, 671, 22))
        self.HorizontalSlider_ArtGAN.setOrientation(QtCore.Qt.Horizontal)
        self.HorizontalSlider_ArtGAN.setObjectName("HorizontalSlider_ArtGAN")
        self.Label_Slider_ArtGAN = QtWidgets.QLabel(self.groupBox_6)
        self.Label_Slider_ArtGAN.setGeometry(QtCore.QRect(710, 580, 71, 21))
        self.Label_Slider_ArtGAN.setObjectName("Label_Slider_ArtGAN")
        self.Button_PerformTraining_ArtGAN = QtWidgets.QPushButton(self.groupBox_6)
        self.Button_PerformTraining_ArtGAN.setGeometry(QtCore.QRect(150, 20, 111, 21))
        self.Button_PerformTraining_ArtGAN.setObjectName("Button_PerformTraining_ArtGAN")
        self.tabWidget.addTab(self.Tab_GAN, "")
        DLArt_GUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DLArt_GUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1384, 21))
        self.menuBar.setObjectName("menuBar")
        DLArt_GUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DLArt_GUI)
        self.mainToolBar.setObjectName("mainToolBar")
        DLArt_GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DLArt_GUI)
        self.statusBar.setObjectName("statusBar")
        DLArt_GUI.setStatusBar(self.statusBar)

        self.retranslateUi(DLArt_GUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DLArt_GUI)

    def retranslateUi(self, DLArt_GUI):
        _translate = QtCore.QCoreApplication.translate
        DLArt_GUI.setWindowTitle(_translate("DLArt_GUI", "Deep Learning Art"))
        self.groupBox.setTitle(_translate("DLArt_GUI", "Database and Patching"))
        self.label_5.setText(_translate("DLArt_GUI", "x"))
        self.label_4.setText(_translate("DLArt_GUI", "Patch Size:"))
        self.label_6.setText(_translate("DLArt_GUI", "Overlap:"))
        self.Button_Patching.setText(_translate("DLArt_GUI", "Perform Patching"))
        self.Button_DB.setText(_translate("DLArt_GUI", "Select Database"))
        self.Label_DB.setText(_translate("DLArt_GUI", "No Database selected"))
        self.Button_OutputPathPatching.setText(_translate("DLArt_GUI", "Output Path"))
        self.Label_OutputPathPatching.setText(_translate("DLArt_GUI", "Output Path"))
        self.Button_MarkingsPath.setText(_translate("DLArt_GUI", "Markings Path"))
        self.Label_MarkingsPath.setText(_translate("DLArt_GUI", "Markings Path"))
        self.RadioButton_MaskLabeling.setText(_translate("DLArt_GUI", "Mask Labeling"))
        self.RadioButton_PatchLabeling.setText(_translate("DLArt_GUI", "Patch Labeling"))
        self.ComboBox_Patching.setItemText(0, _translate("DLArt_GUI", "Select Patching Mode ..."))
        self.ComboBox_Patching.setItemText(1, _translate("DLArt_GUI", "2D"))
        self.ComboBox_Patching.setItemText(2, _translate("DLArt_GUI", "3D"))
        self.label_7.setText(_translate("DLArt_GUI", "x"))
        self.ComboBox_StoreOptions.setItemText(0, _translate("DLArt_GUI", "Do not store on HD"))
        self.ComboBox_StoreOptions.setItemText(1, _translate("DLArt_GUI", "H5PY"))
        self.ComboBox_StoreOptions.setItemText(2, _translate("DLArt_GUI", "Patch based"))
        self.ComboBox_splittingMode.setItemText(0, _translate("DLArt_GUI", "Select Data Spliting ..."))
        self.ComboBox_splittingMode.setItemText(1, _translate("DLArt_GUI", "Simple Random Samples"))
        self.ComboBox_splittingMode.setItemText(2, _translate("DLArt_GUI", "Crossvalidation"))
        self.ComboBox_splittingMode.setItemText(3, _translate("DLArt_GUI", "Patient Crossvalidation"))
        self.Label_SplittingParams.setText(_translate("DLArt_GUI", "Splitting Params"))
        self.GroupBox_TrainNN.setTitle(_translate("DLArt_GUI", "Train Deep Neural Network"))
        self.Button_LearningOutputPath.setText(_translate("DLArt_GUI", "Learning Output Path"))
        self.Label_LearningOutputPath.setText(_translate("DLArt_GUI", "Select Network Output Path!"))
        self.Button_train.setText(_translate("DLArt_GUI", "Train"))
        self.label_13.setText(_translate("DLArt_GUI", "Momentum:"))
        self.CheckBox_Nesterov.setText(_translate("DLArt_GUI", "Nesterov"))
        self.label_14.setText(_translate("DLArt_GUI", "Weight Decay:"))
        self.label.setText(_translate("DLArt_GUI", "Select Multiclasses:"))
        self.CheckBox_Artifacts.setText(_translate("DLArt_GUI", "Artifacts"))
        self.CheckBox_BodyRegion.setText(_translate("DLArt_GUI", "Body Region"))
        self.CheckBox_TWeighting.setText(_translate("DLArt_GUI", "T Weighting"))
        self.CheckBox_DataAugmentation.setText(_translate("DLArt_GUI", "Data Augmentation"))
        self.CheckBox_DataAug_horizontalFlip.setText(_translate("DLArt_GUI", "Horizontal Flip"))
        self.CheckBox_DataAug_verticalFlip.setText(_translate("DLArt_GUI", "Vertical Flip"))
        self.CheckBox_DataAug_Rotation.setText(_translate("DLArt_GUI", "Rotation"))
        self.CheckBox_DataAug_Zoom.setText(_translate("DLArt_GUI", "Zoom"))
        self.CheckBox_DataAug_zcaWeighting.setText(_translate("DLArt_GUI", "ZCA Whitening"))
        self.CheckBox_DataAug_HeightShift.setText(_translate("DLArt_GUI", "Height Shift"))
        self.CheckBox_DataAug_WidthShift.setText(_translate("DLArt_GUI", "Width Shift"))
        self.RadioButton_DataAug_contrastStretching.setText(_translate("DLArt_GUI", "Contrast Stretching"))
        self.RadioButton_DataAug_histogramEq.setText(_translate("DLArt_GUI", "Histogram Eq"))
        self.RadioButton_DataAug_adaptiveEq.setText(_translate("DLArt_GUI", "Adaptive Eq"))
        self.LineEdit_LearningRates.setText(_translate("DLArt_GUI", "0.1,0.01,0.001"))
        self.label_3.setText(_translate("DLArt_GUI", "Learning Rates \"0.1,0.01,0.005\" :"))
        self.label_12.setText(_translate("DLArt_GUI", "Optimizer:"))
        self.ComboBox_Optimizers.setItemText(0, _translate("DLArt_GUI", "SGD"))
        self.ComboBox_Optimizers.setItemText(1, _translate("DLArt_GUI", "RMSprop"))
        self.ComboBox_Optimizers.setItemText(2, _translate("DLArt_GUI", "Adagrad"))
        self.ComboBox_Optimizers.setItemText(3, _translate("DLArt_GUI", "Adadelta"))
        self.ComboBox_Optimizers.setItemText(4, _translate("DLArt_GUI", "Adam"))
        self.LineEdit_BatchSizes.setText(_translate("DLArt_GUI", "128"))
        self.label_2.setText(_translate("DLArt_GUI", "Batch Size/s:"))
        self.label_8.setText(_translate("DLArt_GUI", "Epochs:"))
        self.groupBox_4.setTitle(_translate("DLArt_GUI", "Dataset for Deep Learning"))
        self.Button_useCurrentData.setText(_translate("DLArt_GUI", "Use current data"))
        self.Button_selectDataset.setText(_translate("DLArt_GUI", "Select Dataset"))
        self.Label_currentDataset.setText(_translate("DLArt_GUI", "No Dataset is selected for Deep Learning!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Multiclass), _translate("DLArt_GUI", "Multiclass Classification"))
        self.groupBox_2.setTitle(_translate("DLArt_GUI", "Database and Patching"))
        self.Button_DB_ArtGAN.setText(_translate("DLArt_GUI", "Select Database"))
        self.Label_DB_ArtGAN.setText(_translate("DLArt_GUI", "No Database selected"))
        self.label_9.setText(_translate("DLArt_GUI", "Patch Size:"))
        self.label_10.setText(_translate("DLArt_GUI", "x"))
        self.label_11.setText(_translate("DLArt_GUI", "Overlap:"))
        self.ComboBox_StoreOptions_ArtGAN.setItemText(0, _translate("DLArt_GUI", "Do not store on HD"))
        self.ComboBox_StoreOptions_ArtGAN.setItemText(1, _translate("DLArt_GUI", "H5PY"))
        self.ComboBox_StoreOptions_ArtGAN.setItemText(2, _translate("DLArt_GUI", "Patch based"))
        self.Button_OutputPathPatching_2.setText(_translate("DLArt_GUI", "Output Path"))
        self.Button_Patching_ArtGAN.setText(_translate("DLArt_GUI", "Perform Patching"))
        self.Label_OutputPathPatching_ArtGAN.setText(_translate("DLArt_GUI", "Output Path"))
        self.groupBox_5.setTitle(_translate("DLArt_GUI", "Dataset for Deep Learning"))
        self.Button_useCurrentData_ArtGAN.setText(_translate("DLArt_GUI", "Use current data"))
        self.Button_selectDataset_ArtGAN.setText(_translate("DLArt_GUI", "Select Dataset"))
        self.Label_currentDataset_ArtGAN.setText(_translate("DLArt_GUI", "No Dataset is selected for Deep Learning!"))
        self.groupBox_6.setTitle(_translate("DLArt_GUI", "GAN"))
        self.Button_ShowDataset.setText(_translate("DLArt_GUI", "Show Dataset"))
        self.Label_Slider_ArtGAN.setText(_translate("DLArt_GUI", "0"))
        self.Button_PerformTraining_ArtGAN.setText(_translate("DLArt_GUI", "Perform Training"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_GAN), _translate("DLArt_GUI", "ArtGAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DLArt_GUI = QtWidgets.QMainWindow()
    ui = Ui_DLArt_GUI()
    ui.setupUi(DLArt_GUI)
    DLArt_GUI.show()
    sys.exit(app.exec_())

