# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yannick\Google Drive\Masterarbeit\30_Content\CNNArt\DeepLearningArt\DLArt_GUI\dlart_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DLArt_GUI(object):
    def setupUi(self, DLArt_GUI):
        DLArt_GUI.setObjectName("DLArt_GUI")
        DLArt_GUI.resize(1384, 935)
        self.centralWidget = QtWidgets.QWidget(DLArt_GUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1361, 851))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Multiclass = QtWidgets.QWidget()
        self.Tab_Multiclass.setObjectName("Tab_Multiclass")
        self.groupBox = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 511, 501))
        self.groupBox.setObjectName("groupBox")
        self.SpinBox_PatchX = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchX.setGeometry(QtCore.QRect(90, 241, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchX.setFont(font)
        self.SpinBox_PatchX.setMaximum(500)
        self.SpinBox_PatchX.setProperty("value", 40)
        self.SpinBox_PatchX.setObjectName("SpinBox_PatchX")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.SpinBox_PatchY = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchY.setGeometry(QtCore.QRect(180, 240, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchY.setFont(font)
        self.SpinBox_PatchY.setMaximum(500)
        self.SpinBox_PatchY.setProperty("value", 40)
        self.SpinBox_PatchY.setObjectName("SpinBox_PatchY")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(340, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.SpinBox_PatchOverlapp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.SpinBox_PatchOverlapp.setGeometry(QtCore.QRect(400, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchOverlapp.setFont(font)
        self.SpinBox_PatchOverlapp.setMaximum(1.0)
        self.SpinBox_PatchOverlapp.setSingleStep(0.05)
        self.SpinBox_PatchOverlapp.setProperty("value", 0.5)
        self.SpinBox_PatchOverlapp.setObjectName("SpinBox_PatchOverlapp")
        self.Button_Patching = QtWidgets.QPushButton(self.groupBox)
        self.Button_Patching.setGeometry(QtCore.QRect(370, 450, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Patching.setFont(font)
        self.Button_Patching.setObjectName("Button_Patching")
        self.TreeWidget_Patients = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Patients.setGeometry(QtCore.QRect(10, 78, 151, 151))
        self.TreeWidget_Patients.setObjectName("TreeWidget_Patients")
        self.TreeWidget_Patients.headerItem().setText(0, "1")
        self.TreeWidget_Datasets = QtWidgets.QTreeWidget(self.groupBox)
        self.TreeWidget_Datasets.setGeometry(QtCore.QRect(180, 78, 321, 151))
        self.TreeWidget_Datasets.setObjectName("TreeWidget_Datasets")
        self.TreeWidget_Datasets.headerItem().setText(0, "1")
        self.Button_DB = QtWidgets.QPushButton(self.groupBox)
        self.Button_DB.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_DB.setFont(font)
        self.Button_DB.setObjectName("Button_DB")
        self.Label_DB = QtWidgets.QLabel(self.groupBox)
        self.Label_DB.setGeometry(QtCore.QRect(130, 35, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_DB.setFont(font)
        self.Label_DB.setObjectName("Label_DB")
        self.Button_OutputPathPatching = QtWidgets.QPushButton(self.groupBox)
        self.Button_OutputPathPatching.setGeometry(QtCore.QRect(20, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_OutputPathPatching.setFont(font)
        self.Button_OutputPathPatching.setObjectName("Button_OutputPathPatching")
        self.Label_OutputPathPatching = QtWidgets.QLabel(self.groupBox)
        self.Label_OutputPathPatching.setGeometry(QtCore.QRect(130, 360, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Label_OutputPathPatching.setFont(font)
        self.Label_OutputPathPatching.setObjectName("Label_OutputPathPatching")
        self.Button_MarkingsPath = QtWidgets.QPushButton(self.groupBox)
        self.Button_MarkingsPath.setGeometry(QtCore.QRect(20, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_MarkingsPath.setFont(font)
        self.Button_MarkingsPath.setObjectName("Button_MarkingsPath")
        self.Label_MarkingsPath = QtWidgets.QLabel(self.groupBox)
        self.Label_MarkingsPath.setGeometry(QtCore.QRect(130, 320, 361, 31))
        self.Label_MarkingsPath.setObjectName("Label_MarkingsPath")
        self.RadioButton_MaskLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_MaskLabeling.setEnabled(True)
        self.RadioButton_MaskLabeling.setGeometry(QtCore.QRect(20, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_MaskLabeling.setFont(font)
        self.RadioButton_MaskLabeling.setChecked(True)
        self.RadioButton_MaskLabeling.setObjectName("RadioButton_MaskLabeling")
        self.RadioButton_PatchLabeling = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButton_PatchLabeling.setGeometry(QtCore.QRect(160, 290, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RadioButton_PatchLabeling.setFont(font)
        self.RadioButton_PatchLabeling.setObjectName("RadioButton_PatchLabeling")
        self.ComboBox_Patching = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_Patching.setGeometry(QtCore.QRect(330, 282, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ComboBox_Patching.setFont(font)
        self.ComboBox_Patching.setObjectName("ComboBox_Patching")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.ComboBox_Patching.addItem("")
        self.SpinBox_PatchZ = QtWidgets.QSpinBox(self.groupBox)
        self.SpinBox_PatchZ.setGeometry(QtCore.QRect(270, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_PatchZ.setFont(font)
        self.SpinBox_PatchZ.setProperty("value", 5)
        self.SpinBox_PatchZ.setObjectName("SpinBox_PatchZ")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(250, 240, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ComboBox_StoreOptions = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_StoreOptions.setGeometry(QtCore.QRect(20, 450, 151, 31))
        self.ComboBox_StoreOptions.setObjectName("ComboBox_StoreOptions")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_StoreOptions.addItem("")
        self.ComboBox_splittingMode = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_splittingMode.setGeometry(QtCore.QRect(20, 400, 171, 31))
        self.ComboBox_splittingMode.setObjectName("ComboBox_splittingMode")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.ComboBox_splittingMode.addItem("")
        self.Label_SplittingParams = QtWidgets.QLabel(self.groupBox)
        self.Label_SplittingParams.setGeometry(QtCore.QRect(210, 405, 271, 21))
        self.Label_SplittingParams.setObjectName("Label_SplittingParams")
        self.GroupBox_TrainNN = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.GroupBox_TrainNN.setEnabled(False)
        self.GroupBox_TrainNN.setGeometry(QtCore.QRect(540, 370, 471, 261))
        self.GroupBox_TrainNN.setObjectName("GroupBox_TrainNN")
        self.Button_LearningOutputPath = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_LearningOutputPath.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.Button_LearningOutputPath.setObjectName("Button_LearningOutputPath")
        self.Label_LearningOutputPath = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.Label_LearningOutputPath.setGeometry(QtCore.QRect(150, 75, 311, 21))
        self.Label_LearningOutputPath.setObjectName("Label_LearningOutputPath")
        self.label_2 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_2.setGeometry(QtCore.QRect(20, 109, 71, 31))
        self.label_2.setObjectName("label_2")
        self.SpinBox_BatchSize = QtWidgets.QSpinBox(self.GroupBox_TrainNN)
        self.SpinBox_BatchSize.setGeometry(QtCore.QRect(100, 111, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_BatchSize.setFont(font)
        self.SpinBox_BatchSize.setMaximum(100000000)
        self.SpinBox_BatchSize.setProperty("value", 100)
        self.SpinBox_BatchSize.setObjectName("SpinBox_BatchSize")
        self.label_3 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 221, 31))
        self.label_3.setObjectName("label_3")
        self.LineEdit_LearningRates = QtWidgets.QLineEdit(self.GroupBox_TrainNN)
        self.LineEdit_LearningRates.setGeometry(QtCore.QRect(210, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit_LearningRates.setFont(font)
        self.LineEdit_LearningRates.setObjectName("LineEdit_LearningRates")
        self.label_8 = QtWidgets.QLabel(self.GroupBox_TrainNN)
        self.label_8.setGeometry(QtCore.QRect(220, 110, 55, 31))
        self.label_8.setObjectName("label_8")
        self.SpinBox_Epochs = QtWidgets.QSpinBox(self.GroupBox_TrainNN)
        self.SpinBox_Epochs.setGeometry(QtCore.QRect(280, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBox_Epochs.setFont(font)
        self.SpinBox_Epochs.setMaximum(100000)
        self.SpinBox_Epochs.setProperty("value", 100)
        self.SpinBox_Epochs.setObjectName("SpinBox_Epochs")
        self.Button_train = QtWidgets.QPushButton(self.GroupBox_TrainNN)
        self.Button_train.setGeometry(QtCore.QRect(200, 210, 101, 41))
        self.Button_train.setObjectName("Button_train")
        self.ProgressBar_training = QtWidgets.QProgressBar(self.GroupBox_TrainNN)
        self.ProgressBar_training.setGeometry(QtCore.QRect(310, 220, 151, 21))
        self.ProgressBar_training.setProperty("value", 100)
        self.ProgressBar_training.setObjectName("ProgressBar_training")
        self.ComboBox_DNNs = QtWidgets.QComboBox(self.GroupBox_TrainNN)
        self.ComboBox_DNNs.setGeometry(QtCore.QRect(10, 20, 451, 31))
        self.ComboBox_DNNs.setObjectName("ComboBox_DNNs")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 20, 451, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Tab_Multiclass)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 519, 511, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.Button_useCurrentData = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_useCurrentData.setEnabled(False)
        self.Button_useCurrentData.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.Button_useCurrentData.setObjectName("Button_useCurrentData")
        self.Button_selectDataset = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_selectDataset.setGeometry(QtCore.QRect(140, 30, 361, 31))
        self.Button_selectDataset.setObjectName("Button_selectDataset")
        self.Label_currentDataset = QtWidgets.QLabel(self.groupBox_4)
        self.Label_currentDataset.setGeometry(QtCore.QRect(10, 70, 491, 20))
        self.Label_currentDataset.setObjectName("Label_currentDataset")
        self.tabWidget.addTab(self.Tab_Multiclass, "")
        self.Tab_GAN = QtWidgets.QWidget()
        self.Tab_GAN.setObjectName("Tab_GAN")
        self.tabWidget.addTab(self.Tab_GAN, "")
        DLArt_GUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DLArt_GUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1384, 21))
        self.menuBar.setObjectName("menuBar")
        DLArt_GUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DLArt_GUI)
        self.mainToolBar.setObjectName("mainToolBar")
        DLArt_GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DLArt_GUI)
        self.statusBar.setObjectName("statusBar")
        DLArt_GUI.setStatusBar(self.statusBar)

        self.retranslateUi(DLArt_GUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DLArt_GUI)

    def retranslateUi(self, DLArt_GUI):
        _translate = QtCore.QCoreApplication.translate
        DLArt_GUI.setWindowTitle(_translate("DLArt_GUI", "Deep Learning Art"))
        self.groupBox.setTitle(_translate("DLArt_GUI", "Database and Patching"))
        self.label_5.setText(_translate("DLArt_GUI", "x"))
        self.label_4.setText(_translate("DLArt_GUI", "Patch Size:"))
        self.label_6.setText(_translate("DLArt_GUI", "Overlap:"))
        self.Button_Patching.setText(_translate("DLArt_GUI", "Perform Patching"))
        self.Button_DB.setText(_translate("DLArt_GUI", "Select Database"))
        self.Label_DB.setText(_translate("DLArt_GUI", "No Database selected"))
        self.Button_OutputPathPatching.setText(_translate("DLArt_GUI", "Output Path"))
        self.Label_OutputPathPatching.setText(_translate("DLArt_GUI", "Output Path"))
        self.Button_MarkingsPath.setText(_translate("DLArt_GUI", "Markings Path"))
        self.Label_MarkingsPath.setText(_translate("DLArt_GUI", "Markings Path"))
        self.RadioButton_MaskLabeling.setText(_translate("DLArt_GUI", "Mask Labeling"))
        self.RadioButton_PatchLabeling.setText(_translate("DLArt_GUI", "Patch Labeling"))
        self.ComboBox_Patching.setItemText(0, _translate("DLArt_GUI", "Select Patching Mode ..."))
        self.ComboBox_Patching.setItemText(1, _translate("DLArt_GUI", "2D"))
        self.ComboBox_Patching.setItemText(2, _translate("DLArt_GUI", "3D"))
        self.label_7.setText(_translate("DLArt_GUI", "x"))
        self.ComboBox_StoreOptions.setItemText(0, _translate("DLArt_GUI", "Do not store on HD"))
        self.ComboBox_StoreOptions.setItemText(1, _translate("DLArt_GUI", "H5PY"))
        self.ComboBox_StoreOptions.setItemText(2, _translate("DLArt_GUI", "Patch based"))
        self.ComboBox_splittingMode.setItemText(0, _translate("DLArt_GUI", "Select Data Spliting ..."))
        self.ComboBox_splittingMode.setItemText(1, _translate("DLArt_GUI", "Simple Random Samples"))
        self.ComboBox_splittingMode.setItemText(2, _translate("DLArt_GUI", "Crossvalidation"))
        self.ComboBox_splittingMode.setItemText(3, _translate("DLArt_GUI", "Patient Crossvalidation"))
        self.Label_SplittingParams.setText(_translate("DLArt_GUI", "Splitting Params"))
        self.GroupBox_TrainNN.setTitle(_translate("DLArt_GUI", "Train Deep Neural Network"))
        self.Button_LearningOutputPath.setText(_translate("DLArt_GUI", "Learning Output Path"))
        self.Label_LearningOutputPath.setText(_translate("DLArt_GUI", "Select Network Output Path!"))
        self.label_2.setText(_translate("DLArt_GUI", "Batch Size:"))
        self.label_3.setText(_translate("DLArt_GUI", "Learning Rates \"0.1,0.01,0.005\" :"))
        self.LineEdit_LearningRates.setText(_translate("DLArt_GUI", "0.1,0.01,0.005,0.001"))
        self.label_8.setText(_translate("DLArt_GUI", "Epochs:"))
        self.Button_train.setText(_translate("DLArt_GUI", "Train"))
        self.groupBox_3.setTitle(_translate("DLArt_GUI", "Training Parameters"))
        self.groupBox_4.setTitle(_translate("DLArt_GUI", "Dataset for Deep Learning"))
        self.Button_useCurrentData.setText(_translate("DLArt_GUI", "Use current data"))
        self.Button_selectDataset.setText(_translate("DLArt_GUI", "Select Dataset"))
        self.Label_currentDataset.setText(_translate("DLArt_GUI", "No Dataset is selected for Deep Learning!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Multiclass), _translate("DLArt_GUI", "Multiclass Classification"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_GAN), _translate("DLArt_GUI", "ArtGAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DLArt_GUI = QtWidgets.QMainWindow()
    ui = Ui_DLArt_GUI()
    ui.setupUi(DLArt_GUI)
    DLArt_GUI.show()
    sys.exit(app.exec_())

